// ─────────────────────────────────────────────────────────────
// docs/graphs/generate.ts — the architecture knowledge graphs
// ─────────────────────────────────────────────────────────────
//
//   bun docs/graphs/generate.ts        → re-emits docs/graphs/*.svg
//
// Each graph is a declarative spec rendered through the shared design system
// (lib.ts) — one palette, one visual language across the whole set. These are
// the visual layer of the architecture documentation; the paired prose lives
// (or will live) alongside each graph — see .TODO/KNOWLEDGE_GRAPHS.md.
// ─────────────────────────────────────────────────────────────

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { render, type Graph } from './lib'

const OUT = dirname( fileURLToPath( import.meta.url ) )

const graphs: Graph[] = [

  // ═══ 1 · MEMORY ═══════════════════════════════════════════
  {
    file: 'memory-cycle.svg',
    title: 'Memory — how experience becomes a self',
    subtitle: 'Working memory → episodic consolidation → beliefs; maintenance loops below, recall back into thought on the right',
    width: 1360, height: 780,
    legend: [ 'perceptual', 'memory', 'meta', 'executive', 'llm', 'infra' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 232, label: 'intake',                     cat: 'perceptual' },
      { x: 300,  y: 118, w: 216, h: 232, label: 'short-term',                 cat: 'memory' },
      { x: 556,  y: 118, w: 500, h: 292, label: 'consolidation · long-term',  cat: 'memory' },
      { x: 556,  y: 438, w: 500, h: 232, label: 'maintenance · offline',      cat: 'memory' },
      { x: 1076, y: 118, w: 240, h: 292, label: 'recall into thought',        cat: 'executive' },
    ],
    nodes: [
      { id: 'percepts',  x: 62,   y: 150, label: 'Percepts',               sub: 'senses.*.percept',            cat: 'perceptual' },
      { id: 'exchange',  x: 62,   y: 262, label: 'Conversation turns',     sub: 'audition exchanges',          cat: 'perceptual' },
      { id: 'wm',        x: 318,  y: 205, w: 180, label: 'WorkingMemory',  sub: 'activation · decay',          cat: 'memory' },
      { id: 'consol',    x: 576,  y: 150, w: 196, label: 'EpisodicConsolidator', sub: 'episodes · dedup',      cat: 'memory' },
      { id: 'embed',     x: 576,  y: 280, w: 196, label: 'Embedder',       sub: 'vector encode (live only)',   cat: 'llm', glow: true },
      { id: 'vector',    x: 838,  y: 280, w: 190, label: 'Vector memory',  sub: 'semantic index',              cat: 'memory' },
      { id: 'semantic',  x: 838,  y: 150, w: 190, label: 'SemanticIntegrator', sub: 'beliefs · confidence',    cat: 'memory' },
      { id: 'forget',    x: 576,  y: 470, w: 196, label: 'ForgettingCurve', sub: 'decay · prune',              cat: 'memory' },
      { id: 'dream',     x: 576,  y: 580, w: 196, label: 'DreamSimulator', sub: 'offline replay',              cat: 'memory' },
      { id: 'spaced',    x: 838,  y: 470, w: 190, label: 'SpacedRepetition', sub: 'reinforce on schedule',     cat: 'memory' },
      { id: 'narrator',  x: 838,  y: 580, w: 190, label: 'Autobiographical', sub: 'narrator — the life story', cat: 'meta' },
      { id: 'recall',    x: 1094, y: 150, w: 204, label: 'buildExecutiveContext', sub: '## Relevant Memories', cat: 'executive' },
      { id: 'prompt',    x: 1094, y: 280, w: 204, label: 'Executive & facet prompts', sub: 'master · conversation', cat: 'llm', glow: true },
      { id: 'pma',       x: 1094, y: 560, w: 204, label: 'PMA distill',    sub: 'beliefs · digests · narrative', cat: 'infra' },
    ],
    edges: [
      { from: 'percepts', to: 'wm' },
      { from: 'exchange', to: 'wm',      label: 'WM items' },
      { from: 'wm',       to: 'consol',  label: 'salient items' },
      { from: 'consol',   to: 'embed',   dash: true, label: 'embed', cat: 'llm' },
      { from: 'embed',    to: 'vector',  cat: 'llm' },
      { from: 'consol',   to: 'semantic' },
      { from: 'forget',   to: 'consol',  dash: true, label: 'prune',  fromSide: 'l', toSide: 'l', ext: 30 },
      { from: 'dream',    to: 'consol',  dash: true, label: 'replay', fromSide: 'l', toSide: 'l', ext: 56, at: 0.55 },
      { from: 'spaced',   to: 'semantic', dash: true, label: 'reinforce', fromSide: 'l', toSide: 'l', ext: 26 },
      { from: 'vector',   to: 'recall',  dash: true, label: 'semanticQuery' },
      { from: 'semantic', to: 'recall' },
      { from: 'recall',   to: 'prompt' },
      { from: 'semantic', to: 'pma',     dash: true, fromSide: 'r', toSide: 't', reach: 30 },
      { from: 'narrator', to: 'pma' },
    ],
  },

  // ═══ 2 · EXECUTIVE & FACETS ═══════════════════════════════
  {
    file: 'executive-dual-process.svg',
    title: 'Executive — dual-process thought & facets',
    subtitle: 'One consciousness: master cycle and every focused facet share identity, context and schema — reasoning launches and lands only at tick boundaries',
    width: 1360, height: 780,
    legend: [ 'perceptual', 'executive', 'llm', 'infra' ],
    groups: [
      { x: 284,  y: 118, w: 500, h: 330, label: 'the master cycle',                     cat: 'executive' },
      { x: 824,  y: 118, w: 492, h: 230, label: 'facet machinery — unified inference',  cat: 'executive' },
      { x: 824,  y: 378, w: 492, h: 230, label: 'tick-quantized seams (determinism)',   cat: 'infra' },
    ],
    nodes: [
      { id: 'salience', x: 60,   y: 150, label: 'Salience charge',  sub: 'events accrue pressure',        cat: 'perceptual' },
      { id: 'activate', x: 60,   y: 262, label: 'Activation gate',  sub: 'salience_charged → cycle',      cat: 'executive' },
      { id: 'context',  x: 300,  y: 150, w: 208, label: 'buildExecutiveContext', sub: 'state · goals · memories · abilities', cat: 'executive' },
      { id: 'gate',     x: 300,  y: 262, w: 208, label: 'Effort gate', sub: 'selectProcess: fast | deliberate', cat: 'executive' },
      { id: 'ideate',   x: 560,  y: 150, w: 200, label: 'Ideation (propose)', sub: 'divergent candidates', cat: 'llm', glow: true },
      { id: 'decide',   x: 560,  y: 300, w: 200, label: 'Decision call', sub: 'PromptFactory · LLMDirector', cat: 'llm', glow: true },
      { id: 'commands', x: 560,  y: 470, w: 210, label: 'buildStateCommands', sub: 'goals · beliefs · narrative · ideomotor', cat: 'executive' },
      { id: 'commit',   x: 560,  y: 620, w: 210, label: 'State commit', sub: 'command buffer (serial)',    cat: 'infra' },
      { id: 'recorder', x: 300,  y: 620, w: 208, label: 'Completion recorder', sub: 'record ↔ re-feed (replay)', cat: 'infra' },
      { id: 'creators', x: 60,   y: 470, w: 208, label: 'Creator engines', sub: 'audition · deliberation · planning', cat: 'infra' },
      { id: 'superv',   x: 850,  y: 150, w: 200, label: 'FacetSupervisor', sub: 'budget · reap idle, never busy', cat: 'executive' },
      { id: 'facet',    x: 850,  y: 262, w: 200, label: 'Facet',      sub: 'a focused instance of the SAME self', cat: 'executive' },
      { id: 'report',   x: 1110, y: 150, w: 190, label: 'report()',   sub: 'queued — never launches raw',  cat: 'executive' },
      { id: 'pump',     x: 1110, y: 262, w: 190, label: 'Per-tick pump', sub: 'frozen-snapshot launch',    cat: 'executive' },
      { id: 'inbox',    x: 1110, y: 410, w: 190, label: 'CompletionInbox', sub: 'decisions land at Phase 2', cat: 'executive' },
      { id: 'subs',     x: 1110, y: 528, w: 190, label: 'Subscribers', sub: 'audition reply · deliberation', cat: 'infra' },
      { id: 'sync',     x: 850,  y: 410, w: 200, label: 'Master sync', sub: 'reasoning broadcast to facets', cat: 'executive' },
    ],
    edges: [
      { from: 'salience', to: 'activate' },
      { from: 'activate', to: 'context', toSide: 'l' },
      { from: 'context',  to: 'gate' },
      { from: 'gate',     to: 'ideate',  label: 'deliberate', cat: 'llm', at: 0.3 },
      { from: 'gate',     to: 'decide',  label: 'fast', cat: 'llm' },
      { from: 'ideate',   to: 'decide',  label: 'candidates', cat: 'llm' },
      { from: 'decide',   to: 'commands' },
      { from: 'commands', to: 'commit' },
      { from: 'decide',   to: 'recorder', dash: true, label: 'record', fromSide: 'l', toSide: 't' },
      { from: 'creators', to: 'superv',  label: 'spawnFacet()', fromSide: 'b', toSide: 'b', reach: 90, at: 0.3 },
      { from: 'creators', to: 'report',  dash: true, label: 'setFocus · report', fromSide: 't', toSide: 't', reach: 46, at: 0.22 },
      { from: 'superv',   to: 'facet' },
      { from: 'report',   to: 'pump',    label: 'queued' },
      { from: 'facet',    to: 'pump',    dash: true, label: 'launch' },
      { from: 'pump',     to: 'decide',  dash: true, label: 'same prompt path', cat: 'llm', fromSide: 'b', toSide: 'r', reach: 26, at: 0.6 },
      { from: 'decide',   to: 'inbox',   dash: true, label: 'resolution enqueued', cat: 'llm', fromSide: 'b', toSide: 'l', reach: 40, at: 0.45 },
      { from: 'inbox',    to: 'subs',    label: 'Phase-2 drain' },
      { from: 'commands', to: 'sync',    dash: true },
      { from: 'sync',     to: 'facet',   dash: true },
    ],
  },

  // ═══ 3 · AGENCY ═══════════════════════════════════════════
  {
    file: 'agency-pipeline.svg',
    title: 'Agency — how a Will acts, and learns to act',
    subtitle: 'Actions are found in the situation, not picked from a catalog: affordances compete, intention biases, enaction returns as learning',
    width: 1360, height: 780,
    legend: [ 'world', 'perceptual', 'executive', 'agency', 'llm' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 560, label: 'sources of the field', cat: 'agency' },
      { x: 300,  y: 118, w: 236, h: 400, label: 'perceive · afford',    cat: 'agency' },
      { x: 560,  y: 118, w: 246, h: 330, label: 'compete',              cat: 'agency' },
      { x: 826,  y: 118, w: 250, h: 440, label: 'enact',                cat: 'agency' },
      { x: 1096, y: 118, w: 224, h: 440, label: 'learn',                cat: 'agency' },
    ],
    nodes: [
      { id: 'innate',   x: 62,   y: 150, label: 'Innate schemas',   sub: 'orient · rest · reach-out…',    cat: 'agency' },
      { id: 'external', x: 62,   y: 262, label: 'Host abilities',   sub: 'meaning + priors (+ MCP tools)', cat: 'world' },
      { id: 'perceptS', x: 62,   y: 374, label: 'Percepts · entities', sub: 'salient things & people',    cat: 'perceptual' },
      { id: 'ideo',     x: 62,   y: 486, label: 'Ideomotor intents', sub: 'imagined acts + conscious args', cat: 'executive' },
      { id: 'planp',    x: 62,   y: 598, label: 'Plan priors',      sub: 'frontier-step bias',            cat: 'executive' },
      { id: 'repert',   x: 318,  y: 205, w: 200, label: 'SchemaRepertoire', sub: 'innate + external + learned', cat: 'agency' },
      { id: 'synth',    x: 318,  y: 400, w: 200, label: 'AffordanceSynthesizer', sub: 'the field — attention-capped', cat: 'agency' },
      { id: 'delib',    x: 578,  y: 180, w: 210, label: 'DeliberationEngine', sub: 'System 2 via a unified facet', cat: 'llm', glow: true },
      { id: 'selector', x: 578,  y: 360, w: 210, label: 'ActionSelector', sub: 'goal + reward + drive − cost − risk', cat: 'agency' },
      { id: 'comm',     x: 846,  y: 180, w: 210, label: 'ProactiveCommunicator', sub: 'communicate → outbox',  cat: 'social' },
      { id: 'motor',    x: 846,  y: 360, w: 210, label: 'MotorSchemaExecutor', sub: 'stance · communicate · external', cat: 'agency' },
      { id: 'invoke',   x: 846,  y: 490, w: 210, label: 'Effector invocation', sub: 'the HOST runs the action',  cat: 'world' },
      { id: 'ack',      x: 1112, y: 490, w: 192, label: 'Execution ack', sub: 'outcome + metrics',          cat: 'world' },
      { id: 'reaff',    x: 1112, y: 360, w: 192, label: 'ReafferenceEngine', sub: 'surprise = predicted − actual', cat: 'agency' },
      { id: 'skills',   x: 1112, y: 205, w: 192, label: 'LearnedSkill', sub: 'value · habit · param priors', cat: 'agency' },
    ],
    edges: [
      { from: 'innate',   to: 'repert' },
      { from: 'external', to: 'repert' },
      { from: 'repert',   to: 'synth',   label: 'enactable schemas' },
      { from: 'perceptS', to: 'synth',   label: 'bind targets' },
      { from: 'ideo',     to: 'synth',   label: 'pre-activate (+args)' },
      { from: 'planp',    to: 'synth',   label: 'bias', toSide: 'b', reach: 10 },
      { from: 'synth',    to: 'selector', label: 'affordances' },
      { from: 'selector', to: 'delib',   label: 'contested · high-stakes', cat: 'llm' },
      { from: 'delib',    to: 'motor',   label: 'chosen intent', cat: 'llm' },
      { from: 'selector', to: 'motor',   label: 'System 1 — habitual', fromSide: 'b', toSide: 'b', ext: 40 },
      { from: 'motor',    to: 'comm',    label: 'communicate' },
      { from: 'motor',    to: 'invoke',  label: 'external' },
      { from: 'invoke',   to: 'ack' },
      { from: 'ack',      to: 'reaff',   label: 'reafference' },
      { from: 'motor',    to: 'reaff',   dash: true, label: 'prediction', fromSide: 't', toSide: 't', ext: 30 },
      { from: 'reaff',    to: 'skills' },
      { from: 'skills',   to: 'repert',  dash: true, label: 'proceduralize → composites', fromSide: 't', toSide: 't', ext: 40, at: 0.45 },
      // EXAFFERENCE: an unpredicted world event doesn't just field a challenger —
      // it softens/revokes the current commitment. Full story: exafference-loop.svg.
      { from: 'perceptS', to: 'selector', dash: true, label: 'exafferent rupture — lets go', fromSide: 'b', toSide: 'b', via: { x: 480, y: 560 } },
    ],
  },

  // ═══ 4 · AUDITION ═════════════════════════════════════════
  {
    file: 'audition-conversation.svg',
    title: 'Audition — how a conversation flows through the mind',
    subtitle: 'Deliver → perceive → one focused facet reasons → the reply lands tick-quantized in the outbox — and the exchange becomes memory',
    width: 1360, height: 780,
    legend: [ 'world', 'perceptual', 'executive', 'llm', 'memory' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 430, label: 'host boundary',          cat: 'world' },
      { x: 300,  y: 118, w: 236, h: 430, label: 'perception · salience',  cat: 'perceptual' },
      { x: 556,  y: 118, w: 250, h: 430, label: 'the facet turn',         cat: 'executive' },
      { x: 826,  y: 118, w: 494, h: 320, label: 'the reply path',         cat: 'llm' },
      { x: 826,  y: 468, w: 494, h: 180, label: 'into memory',            cat: 'memory' },
    ],
    nodes: [
      { id: 'host',     x: 62,   y: 150, label: 'Host / interlocutor', sub: 'say · perceive · MCP · HTTP',  cat: 'world' },
      { id: 'stem',     x: 62,   y: 290, label: 'WillStem.ingestText', sub: 'sensory controller',           cat: 'infra' },
      { id: 'grants',   x: 62,   y: 430, label: 'AccessGrants',      sub: "'listen' granted?",              cat: 'agency' },
      { id: 'percept',  x: 318,  y: 290, w: 200, label: 'Language percept', sub: 'salience-weighted',       cat: 'perceptual' },
      { id: 'digest',   x: 318,  y: 430, w: 200, label: 'Thread digest', sub: 'rolling conversation state', cat: 'memory' },
      { id: 'turnq',    x: 318,  y: 150, w: 200, label: 'Turn queue',  sub: 'one turn per entity',          cat: 'infra' },
      { id: 'attach',   x: 62,   y: 600, label: 'Attachment · goals', sub: 'closeness + topic overlap',     cat: 'affective' },
      { id: 'focus',    x: 576,  y: 150, w: 210, label: 'Focus + recall query', sub: 'the live message drives recall', cat: 'executive' },
      { id: 'facet',    x: 576,  y: 290, w: 210, label: 'Conversation facet', sub: 'spawned from the executive', cat: 'executive' },
      { id: 'quant',    x: 576,  y: 430, w: 210, label: 'report → pump → inbox', sub: 'tick-quantized launch & landing', cat: 'executive' },
      { id: 'reason',   x: 846,  y: 220, w: 200, label: 'Reply reasoning', sub: '[REPLY_TEXT] dialect',     cat: 'llm', glow: true },
      { id: 'stream',   x: 1116, y: 150, w: 188, label: 'Chunk stream', sub: 'only reply text escapes',     cat: 'world' },
      { id: 'writer',   x: 846,  y: 360, w: 200, label: 'OutboxWriter', sub: 'bubbles · threadId',          cat: 'infra' },
      { id: 'outbox',   x: 1116, y: 360, w: 188, label: 'Outbox → host', sub: 'delivery + ack loop',        cat: 'world' },
      { id: 'exchange', x: 846,  y: 528, w: 200, label: 'Exchange memory', sub: 'WM item → episodic → vector', cat: 'memory' },
      { id: 'recallq',  x: 1116, y: 528, w: 188, label: 'Next-turn recall', sub: 'the past shapes the reply', cat: 'memory' },
    ],
    edges: [
      { from: 'host',    to: 'stem' },
      { from: 'stem',    to: 'grants',  label: 'gate' },
      { from: 'grants',  to: 'percept', label: 'allowed', fromSide: 'r', toSide: 'l' },
      { from: 'stem',    to: 'turnq',   dash: true, label: 'arm turn', fromSide: 'r', toSide: 'l', reach: 10 },
      { from: 'percept', to: 'digest',  label: 'append user turn' },
      { from: 'attach',  to: 'percept', dash: true, label: 'salience inputs', fromSide: 'r', toSide: 'b', reach: 24 },
      { from: 'percept', to: 'facet' },
      { from: 'turnq',   to: 'facet',   dash: true, fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'digest',  to: 'focus',   dash: true, label: 'context', fromSide: 't', toSide: 'l', reach: 20, at: 0.35 },
      { from: 'focus',   to: 'facet' },
      { from: 'facet',   to: 'quant',   label: 'report' },
      { from: 'quant',   to: 'reason',  label: 'launch @ tick', cat: 'llm' },
      { from: 'reason',  to: 'stream',  dash: true, label: 'tokens', cat: 'llm' },
      { from: 'reason',  to: 'writer',  label: 'decision lands (Phase 2)', at: 0.55 },
      { from: 'writer',  to: 'outbox' },
      { from: 'writer',  to: 'exchange', dash: true, label: 'exchange' },
      { from: 'exchange', to: 'recallq', dash: true },
    ],
  },

  // ═══ 5 · BODY & FEELING ═══════════════════════════════════
  {
    file: 'affect-body.svg',
    title: 'Body & feeling — regulation and affect',
    subtitle: 'Seven evaluators blend into a real affective state; the body’s budgets gate thought, attention and action — mood is state, not a prompt string',
    width: 1360, height: 830,
    legend: [ 'regulatory', 'affective', 'executive', 'llm', 'world' ],
    groups: [
      { x: 296,  y: 108, w: 226, h: 500, label: 'regulatory — the body', cat: 'regulatory' },
      { x: 556,  y: 108, w: 226, h: 660, label: 'affective evaluators',  cat: 'affective' },
      { x: 1096, y: 108, w: 226, h: 560, label: 'what feeling touches',  cat: 'executive' },
    ],
    nodes: [
      { id: 'events',  x: 60,   y: 200, label: 'Percepts & outcomes', sub: 'what just happened',        cat: 'perceptual' },
      { id: 'body',    x: 60,   y: 360, label: 'Body metrics',   sub: 'energy · sleep · stress',        cat: 'infra' },
      { id: 'energy',  x: 310,  y: 140, w: 196, label: 'EnergyRegulator',  sub: 'actions cost · rest restores', cat: 'regulatory' },
      { id: 'sleep',   x: 310,  y: 232, w: 196, label: 'SleepPressure',    sub: 'cognitive capacity',   cat: 'regulatory' },
      { id: 'circ',    x: 310,  y: 324, w: 196, label: 'CircadianOscillator', sub: 'phase · time of day', cat: 'regulatory' },
      { id: 'stress',  x: 310,  y: 416, w: 196, label: 'StressRegulator',  sub: 'load · decay',         cat: 'regulatory' },
      { id: 'attn',    x: 310,  y: 508, w: 196, label: 'AttentionAllocator', sub: 'capacity budget',    cat: 'regulatory' },
      { id: 'threat',  x: 570,  y: 140, w: 196, label: 'Threat',      sub: 'danger appraisal',      cat: 'affective' },
      { id: 'reward',  x: 570,  y: 230, w: 196, label: 'Reward',      sub: 'gain appraisal',        cat: 'affective' },
      { id: 'loss',    x: 570,  y: 320, w: 196, label: 'Loss',        sub: 'what was taken',        cat: 'affective' },
      { id: 'frust',   x: 570,  y: 410, w: 196, label: 'Frustration', sub: 'blocked intentions',    cat: 'affective' },
      { id: 'attach2', x: 570,  y: 500, w: 196, label: 'Attachment',  sub: 'bonds · belonging',     cat: 'affective' },
      { id: 'aesth',   x: 570,  y: 590, w: 196, label: 'Aesthetic',   sub: 'curiosity · boredom',   cat: 'affective' },
      { id: 'moral',   x: 570,  y: 680, w: 196, label: 'Moral',       sub: 'values violated?',      cat: 'affective' },
      { id: 'blend',   x: 836,  y: 400, w: 210, label: 'AffectiveBlender', sub: 'valence · arousal · dominance · blends', cat: 'affective', glow: true },
      { id: 'effort',  x: 836,  y: 150, w: 210, label: 'Effort gate & caps', sub: 'quality modulation · field width', cat: 'executive' },
      { id: 'prompt2', x: 1110, y: 150, w: 196, label: 'Executive prompt', sub: 'mood colors thought',  cat: 'llm', glow: true },
      { id: 'select2', x: 1110, y: 290, w: 196, label: 'Action selection', sub: 'valence priors · risk', cat: 'agency' },
      { id: 'salW',    x: 1110, y: 430, w: 196, label: 'Percept salience', sub: 'attention weighting',  cat: 'perceptual' },
      { id: 'emit',    x: 1110, y: 570, w: 196, label: "on('emotion')",   sub: 'hosts observe affect',  cat: 'world' },
    ],
    edges: [
      { from: 'events', to: 'threat',  label: 'feeds all seven', at: 0.45 },
      { from: 'body',   to: 'energy',  fromSide: 't', toSide: 'l', reach: 12 },
      { from: 'body',   to: 'stress',  label: 'load' },
      { from: 'circ',   to: 'sleep',   dash: true },
      { from: 'threat', to: 'blend' },
      { from: 'reward', to: 'blend' },
      { from: 'loss',   to: 'blend' },
      { from: 'frust',  to: 'blend' },
      { from: 'attach2', to: 'blend' },
      { from: 'aesth',  to: 'blend' },
      { from: 'moral',  to: 'blend' },
      { from: 'energy', to: 'effort', fromSide: 't', toSide: 't', ext: 36, label: 'budgets', at: 0.72 },
      { from: 'attn',   to: 'select2', dash: true, label: 'attention cap', fromSide: 'b', toSide: 'b', ext: 200, at: 0.55 },
      { from: 'stress', to: 'blend',  dash: true, label: 'arousal', fromSide: 'r', toSide: 'l', at: 0.82 },
      { from: 'effort', to: 'prompt2' },
      { from: 'blend',  to: 'prompt2', fromSide: 'r', toSide: 'b', reach: 8 },
      { from: 'blend',  to: 'select2' },
      { from: 'blend',  to: 'salW' },
      { from: 'blend',  to: 'emit',   fromSide: 'b', toSide: 'l', reach: 16 },
    ],
  },

  // ═══ 6 · THE TICK ═════════════════════════════════════════
  {
    file: 'determinism-tick.svg',
    title: 'The tick — command-buffer determinism & replay',
    subtitle: 'Serial engines write commands, never state; async LLM chains launch and land only at tick boundaries; a transcript makes any life re-runnable byte-for-byte',
    width: 1360, height: 700,
    legend: [ 'infra', 'executive', 'llm', 'world' ],
    groups: [
      { x: 284,  y: 118, w: 520, h: 440, label: 'one tick — serial & pure',          cat: 'infra' },
      { x: 834,  y: 248, w: 226, h: 310, label: 'async chains, quantized',           cat: 'executive' },
      { x: 1090, y: 118, w: 226, h: 440, label: 'the replay seam',                   cat: 'world' },
    ],
    nodes: [
      { id: 'clock',   x: 60,   y: 150, w: 204, label: 'Clock',        sub: 'wall interval | fixed Δ (replay)', cat: 'infra' },
      { id: 'prng',    x: 60,   y: 290, w: 204, label: 'Seeded PRNG',  sub: 'context.random(), never Math.random', cat: 'infra' },
      { id: 'orch',    x: 300,  y: 150, w: 214, label: 'CognitiveOrchestrator', sub: 'engines in priority order', cat: 'infra', glow: true },
      { id: 'engines', x: 300,  y: 290, w: 214, label: 'Engines react()', sub: 'frozen state → commands',  cat: 'executive' },
      { id: 'buffer',  x: 300,  y: 430, w: 214, label: 'Command buffer', sub: 'no in-place writes',        cat: 'infra' },
      { id: 'valid',   x: 574,  y: 430, w: 200, label: 'Validators',  sub: 'abort ⇒ whole tick discarded', cat: 'infra' },
      { id: 'commit2', x: 574,  y: 290, w: 200, label: 'Commit',      sub: 'snapshot (COW) · metrics',     cat: 'infra' },
      { id: 'phase2',  x: 574,  y: 150, w: 200, label: 'Phase 2 — inbox drain', sub: 'facet effects land here', cat: 'executive' },
      { id: 'pump3',   x: 850,  y: 320, w: 190, label: 'Pump · CompletionInbox', sub: 'launch @ tick · land @ Phase 2', cat: 'executive' },
      { id: 'llm3',    x: 850,  y: 470, w: 190, label: 'LLM calls',   sub: 'async — resolve off-tick',     cat: 'llm', glow: true },
      { id: 'rec3',    x: 1106, y: 470, w: 194, label: 'Completion recorder', sub: 'transcript of every call', cat: 'infra' },
      { id: 'refeed',  x: 1106, y: 320, w: 194, label: 'Re-feed source', sub: 'prompt-keyed · strict',     cat: 'infra' },
      { id: 'replay',  x: 1106, y: 150, w: 194, label: 'Byte-identical replay', sub: 'same seed + inputs ⇒ same mind', cat: 'world', glow: true },
    ],
    edges: [
      { from: 'clock',   to: 'orch' },
      { from: 'prng',    to: 'engines', dash: true },
      { from: 'orch',    to: 'engines', label: 'tick N' },
      { from: 'engines', to: 'buffer' },
      { from: 'buffer',  to: 'valid' },
      { from: 'valid',   to: 'commit2', label: 'ok' },
      { from: 'commit2', to: 'phase2' },
      { from: 'phase2',  to: 'orch',   dash: true, label: 'tick N+1', fromSide: 't', toSide: 't', ext: 34 },
      { from: 'engines', to: 'pump3',  dash: true, label: 'react() pumps', fromSide: 'b', toSide: 'l', reach: 36, at: 0.62 },
      { from: 'pump3',   to: 'llm3',   cat: 'llm', label: 'launch' },
      { from: 'llm3',    to: 'pump3',  dash: true, cat: 'llm', label: 'enqueue', fromSide: 'r', toSide: 'r', ext: 24 },
      { from: 'pump3',   to: 'phase2', dash: true, cat: 'llm', label: 'drained @ Phase 2', fromSide: 't', toSide: 'r', ext: 55 },
      { from: 'llm3',    to: 'rec3',   dash: true, label: 'record' },
      { from: 'rec3',    to: 'refeed', label: 'transcript' },
      { from: 'refeed',  to: 'llm3',   dash: true, label: 'replay serves', fromSide: 'l', toSide: 't', reach: 8, at: 0.5 },
      { from: 'refeed',  to: 'replay' },
    ],
  },

  // ═══ 7 · PMA ══════════════════════════════════════════════
  {
    file: 'pma-lifecycle.svg',
    title: 'PMA — the Persistent Mind Artifact',
    subtitle: 'Distill a living mind into a portable artifact; wake the same self anywhere — identity, memory, relationships and skill survive the boundary',
    width: 1360, height: 660,
    legend: [ 'world', 'infra', 'executive', 'memory', 'social', 'agency' ],
    groups: [
      { x: 44,  y: 118, w: 760, h: 470, label: 'the lifecycle',        cat: 'infra' },
      { x: 826, y: 118, w: 494, h: 470, label: 'what travels — the self', cat: 'memory' },
    ],
    nodes: [
      { id: 'hosts',   x: 62,   y: 150, w: 190, label: 'Hosts',       sub: 'SDK · MCP · sidecar · backend', cat: 'world' },
      { id: 'living',  x: 62,   y: 330, w: 190, label: 'A living Will', sub: 'ticking · accreting',        cat: 'executive', glow: true },
      { id: 'distill', x: 330,  y: 210, w: 190, label: 'Distill',     sub: 'save() — non-destructive · hibernate()', cat: 'infra' },
      { id: 'artifact', x: 590, y: 330, w: 190, label: 'PMA artifact', sub: 'a portable JSON self',        cat: 'memory', glow: true },
      { id: 'wake',    x: 330,  y: 460, w: 190, label: 'Wake',        sub: 'paused assembly → load → resume', cat: 'infra' },
      { id: 'eval',    x: 590,  y: 480, w: 190, label: 'Reconstruction eval', sub: 'fidelity report — verified restore', cat: 'infra' },
      { id: 'ident',   x: 856,  y: 150, w: 200, label: 'Identity & traits', sub: 'developed, not configured', cat: 'meta' },
      { id: 'belief2', x: 856,  y: 260, w: 200, label: 'Beliefs & memories', sub: 'semantic + episodic digests', cat: 'memory' },
      { id: 'bonds',   x: 856,  y: 370, w: 200, label: 'Relationships', sub: 'bonds · reputations · dossiers', cat: 'social' },
      { id: 'skills3', x: 856,  y: 480, w: 200, label: 'Skills & composites', sub: 'learned competence',   cat: 'agency' },
      { id: 'narr2',   x: 1106, y: 315, w: 194, label: 'Narrative & persona prior', sub: 'the story of me', cat: 'meta' },
    ],
    edges: [
      { from: 'hosts',   to: 'distill', dash: true, label: 'shutdown', fromSide: 'r', toSide: 't', reach: 10 },
      { from: 'hosts',   to: 'living',  dash: true, label: 'boot' },
      { from: 'living',  to: 'distill', fromSide: 't', toSide: 'l', reach: 16 },
      { from: 'distill', to: 'artifact', fromSide: 'r', toSide: 't', reach: 16 },
      { from: 'artifact', to: 'wake',   fromSide: 'b', toSide: 'r', reach: 16 },
      { from: 'wake',    to: 'living',  label: 'the SAME self', fromSide: 'l', toSide: 'b', reach: 16 },
      { from: 'artifact', to: 'eval',   dash: true, label: 'runPMAEval', fromSide: 'b', toSide: 't', reach: 4 },
      { from: 'artifact', to: 'ident',  fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'artifact', to: 'belief2', fromSide: 'r', toSide: 'l' },
      { from: 'artifact', to: 'bonds',  fromSide: 'r', toSide: 'l' },
      { from: 'artifact', to: 'skills3', fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'belief2', to: 'narr2',   dash: true, fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'bonds',   to: 'narr2',   dash: true, fromSide: 'r', toSide: 'b', reach: 8 },
    ],
  },

  // ═══ 8 · THE COMPOSITION (capstone) ═══════════════════════
  {
    file: 'composition.svg',
    title: 'Will — the whole composition',
    subtitle: 'From any host surface, through the stem, onto one deterministic tick — where forty engines make a mind. The LLM is a component, recruited — never the substrate',
    width: 1360, height: 960,
    legend: [ 'world', 'infra', 'llm', 'memory', 'executive', 'agency' ],
    groups: [
      { x: 44,  y: 108, w: 1272, h: 130, label: 'hosts & world',                        cat: 'world' },
      { x: 44,  y: 258, w: 1272, h: 120, label: 'surfaces — one paradigm, four doors',  cat: 'infra' },
      { x: 44,  y: 398, w: 1272, h: 120, label: 'stem · tick · seams',                  cat: 'infra' },
      { x: 44,  y: 538, w: 1272, h: 330, label: 'the mind — 40+ engines on one tick',   cat: 'executive' },
    ],
    nodes: [
      { id: 'claude',  x: 66,   y: 146, w: 196, label: 'Claude Desktop / Code', sub: 'an MCP client',      cat: 'world' },
      { id: 'app',     x: 300,  y: 146, w: 170, label: 'Your app',      sub: 'Node / TypeScript',          cat: 'world' },
      { id: 'anylang', x: 508,  y: 146, w: 190, label: 'Any language',  sub: 'Python · Go · game server',  cat: 'world' },
      { id: 'studio',  x: 736,  y: 146, w: 210, label: 'Mindot backend / Studio', sub: 'hosted minds',     cat: 'world' },
      { id: 'mcptool', x: 984,  y: 146, w: 200, label: 'External MCP tools', sub: 'employed as abilities', cat: 'world' },
      { id: 'mcp',     x: 66,   y: 296, w: 196, label: 'will mcp',      sub: 'perceive · next_utterance',  cat: 'infra' },
      { id: 'facade',  x: 300,  y: 296, w: 170, label: 'Will facade',   sub: 'projections · PMA',          cat: 'infra' },
      { id: 'serve',   x: 508,  y: 296, w: 190, label: 'will serve',    sub: 'HTTP + SSE · Docker',        cat: 'infra' },
      { id: 'transp',  x: 736,  y: 296, w: 210, label: 'Transports',    sub: 'loopback · socket.io · stream', cat: 'infra' },
      { id: 'bridge',  x: 984,  y: 296, w: 200, label: 'connectMcpEffectors', sub: '@mindot/will/mcp',     cat: 'agency' },
      { id: 'stem2',   x: 66,   y: 436, w: 300, label: 'WillStem — the body', sub: 'ingest · outbox · effectors · PMA · replay tracts', cat: 'infra', glow: true },
      { id: 'orch2',   x: 430,  y: 436, w: 240, label: 'Tick orchestrator', sub: 'serial · command buffer · seeded', cat: 'infra' },
      { id: 'llm4',    x: 736,  y: 436, w: 210, label: 'LLMDirector',   sub: 'gate · recorder · mock | live', cat: 'llm', glow: true },
      { id: 'pma2',    x: 1010, y: 436, w: 174, label: 'PMA',           sub: 'distill ⇄ wake',             cat: 'memory', glow: true },
      { id: 'reg',     x: 80,   y: 586, w: 280, label: 'Regulatory ×5', sub: 'energy · sleep · circadian · stress · attention', cat: 'regulatory' },
      { id: 'perc',    x: 400,  y: 586, w: 300, label: 'Perceptual ×4 + Senses ×5', sub: 'extero · intero · social · novelty · audition…', cat: 'perceptual' },
      { id: 'aff',     x: 740,  y: 586, w: 260, label: 'Affective ×8',  sub: 'seven evaluators + blender', cat: 'affective' },
      { id: 'mem',     x: 1040, y: 586, w: 250, label: 'Memory ×6',     sub: 'WM · episodic · semantic · dream…', cat: 'memory' },
      { id: 'exec',    x: 80,   y: 736, w: 300, label: 'Executive & planning ×5', sub: 'dual-process · facets · plans · inhibition', cat: 'executive' },
      { id: 'agen',    x: 420,  y: 736, w: 280, label: 'Agency ×6',     sub: 'afford · select · deliberate · enact · learn', cat: 'agency' },
      { id: 'metac',   x: 740,  y: 736, w: 280, label: 'Meta-cognitive ×6', sub: 'introspection → persona prior', cat: 'meta' },
      { id: 'soc',     x: 1060, y: 736, w: 230, label: 'Social ×4',     sub: 'ToM · empathy · reputation · dossiers', cat: 'social' },
    ],
    edges: [
      { from: 'claude',  to: 'mcp' },
      { from: 'app',     to: 'facade' },
      { from: 'anylang', to: 'serve' },
      { from: 'studio',  to: 'transp' },
      { from: 'mcptool', to: 'bridge' },
      { from: 'mcp',     to: 'stem2' },
      { from: 'facade',  to: 'stem2' },
      { from: 'serve',   to: 'stem2', fromSide: 'b', toSide: 't', reach: 10 },
      { from: 'transp',  to: 'stem2', fromSide: 'b', toSide: 't', reach: 10 },
      { from: 'bridge',  to: 'agen',  dash: true, label: 'tools become abilities', fromSide: 'r', toSide: 't', via: { x: 1020, y: 690 } },
      { from: 'stem2',   to: 'orch2', label: 'tick' },
      { from: 'orch2',   to: 'perc',  label: 'every tick', fromSide: 'b', toSide: 't' },
      { from: 'llm4',    to: 'exec',  dash: true, cat: 'llm', fromSide: 'b', toSide: 'l', via: { x: 70, y: 528 } },
      { from: 'pma2',    to: 'stem2', dash: true, cat: 'memory', fromSide: 't', toSide: 't', ext: 26, at: 0.5, label: 'hibernate ⇄ wake' },
      { from: 'reg',     to: 'perc' },
      { from: 'perc',    to: 'aff' },
      { from: 'aff',     to: 'mem' },
      { from: 'mem',     to: 'exec',  label: 'context', fromSide: 'b', toSide: 't', via: { x: 720, y: 712 } },
      { from: 'exec',    to: 'agen' },
      { from: 'agen',    to: 'metac' },
      { from: 'metac',   to: 'soc' },
      { from: 'agen',    to: 'stem2', dash: true, label: 'outbox', fromSide: 't', toSide: 'b', reach: 30, at: 0.75 },
      { from: 'metac',   to: 'exec',  dash: true, label: 'writes back into the apparatus', fromSide: 'b', toSide: 'b', reach: 60, at: 0.5 },
    ],
  },

  // ═══ 9 · META-COGNITION ═══════════════════════════════════
  {
    file: 'meta-cognition.svg',
    title: 'Meta-cognition — the loop that closes',
    subtitle: 'The mind observes its own thinking, distills who it is becoming, and writes back into the apparatus — base configs never mutate; the prior accretes',
    width: 1360, height: 700,
    legend: [ 'executive', 'agency', 'meta', 'llm', 'infra' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 400, label: 'what it observes',       cat: 'infra' },
      { x: 300,  y: 118, w: 236, h: 512, label: 'the observers',          cat: 'meta' },
      { x: 560,  y: 118, w: 246, h: 420, label: 'reflection',             cat: 'meta' },
      { x: 1086, y: 118, w: 230, h: 512, label: 'what changes',           cat: 'infra' },
    ],
    nodes: [
      { id: 'exout',   x: 62,   y: 150, label: 'Executive output',  sub: 'reasoning · actions · confidence', cat: 'executive' },
      { id: 'outc3',   x: 62,   y: 290, label: 'Action outcomes',   sub: 'success · surprise',            cat: 'agency' },
      { id: 'lived',   x: 62,   y: 430, label: 'State & metrics',   sub: 'what the body lived',           cat: 'infra' },
      { id: 'selfm',   x: 318,  y: 150, w: 200, label: 'SelfModelUpdater', sub: 'traits develop from evidence', cat: 'meta' },
      { id: 'confc',   x: 318,  y: 270, w: 200, label: 'ConfidenceCalibrator', sub: 'predicted vs actual', cat: 'meta' },
      { id: 'biasd',   x: 318,  y: 390, w: 200, label: 'BiasDetector', sub: 'patterns in reasoning',      cat: 'meta' },
      { id: 'narr3',   x: 318,  y: 540, w: 200, label: 'AutobiographicalNarrator', sub: 'themes of the life story', cat: 'meta' },
      { id: 'introf',  x: 578,  y: 150, w: 210, label: 'INTROSPECTION block', sub: 'inside the single executive call', cat: 'llm', glow: true },
      { id: 'intro3',  x: 578,  y: 300, w: 210, label: 'IntrospectionEngine', sub: 'satellite — no LLM call of its own', cat: 'meta' },
      { id: 'persona2', x: 578, y: 460, w: 210, label: 'PersonaConsolidator', sub: 'distills the durable persona', cat: 'meta' },
      { id: 'prior3',  x: 848,  y: 310, w: 200, label: 'persona-prior', sub: 'learned deltas — base never mutates', cat: 'meta', glow: true },
      { id: 'effp',    x: 1104, y: 150, w: 194, label: 'Effective params', sub: 'base ⊕ prior — every engine reads', cat: 'infra' },
      { id: 'gate4',   x: 1104, y: 290, w: 194, label: 'Effort gate', sub: 'deliberateThreshold shifts',   cat: 'executive' },
      { id: 'traitp',  x: 1104, y: 430, w: 194, label: 'Prompt trait bands', sub: '“markedly curious” — self-knowledge', cat: 'llm' },
      { id: 'salien',  x: 1104, y: 556, w: 194, label: 'Salience & thresholds', sub: 'perception itself re-tunes', cat: 'perceptual' },
    ],
    edges: [
      { from: 'exout',  to: 'selfm' },
      { from: 'exout',  to: 'biasd',  dash: true, fromSide: 'b', toSide: 'l', reach: 10 },
      { from: 'outc3',  to: 'confc',  label: 'calibrate' },
      { from: 'lived',  to: 'selfm',  dash: true, fromSide: 't', toSide: 'b', via: { x: 288, y: 330 } },
      { from: 'selfm',  to: 'introf' },
      { from: 'confc',  to: 'introf' },
      { from: 'introf', to: 'intro3', label: 'harvested when fresh', cat: 'llm' },
      { from: 'biasd',  to: 'intro3', dash: true, label: 'detected biases' },
      { from: 'narr3',  to: 'persona2', dash: true, label: 'themes' },
      { from: 'intro3', to: 'persona2', label: 'lessons · biases' },
      { from: 'persona2', to: 'prior3' },
      { from: 'prior3', to: 'effp',   label: '⊕' },
      { from: 'effp',   to: 'gate4' },
      { from: 'effp',   to: 'salien', dash: true, fromSide: 'r', toSide: 'r', ext: 30 },
      { from: 'selfm',  to: 'traitp', dash: true, label: 'traitStats', fromSide: 't', toSide: 't', ext: 36, at: 0.85 },
      { from: 'gate4',  to: 'exout',  dash: true, label: 'the apparatus changes — next cycle thinks differently', fromSide: 'b', toSide: 'b', via: { x: 660, y: 650 } },
    ],
  },

  // ═══ 10 · EXECUTIVE ⇄ AGENCY SEAM ═════════════════════════
  {
    file: 'executive-agency-seam.svg',
    title: 'Where intention meets action — the executive ⇄ agency seam',
    subtitle: 'The mind sees what is afforded; conscious intent pre-activates with args; plans bias; the field still decides — and outcomes teach both sides',
    width: 1360, height: 720,
    legend: [ 'executive', 'agency', 'llm' ],
    groups: [
      { x: 44,   y: 118, w: 500, h: 540, label: 'the deliberate self (System 2)', cat: 'executive' },
      { x: 584,  y: 118, w: 732, h: 540, label: 'the acting substrate (agency)',  cat: 'agency' },
    ],
    nodes: [
      { id: 'abil',    x: 62,   y: 150, w: 210, label: 'Abilities in context', sub: '## Abilities Available Now', cat: 'executive' },
      { id: 'actarg',  x: 62,   y: 290, w: 210, label: 'Action with conscious args', sub: '{"type":"search","args":{…}}', cat: 'executive' },
      { id: 'planE',   x: 62,   y: 430, w: 210, label: 'PlanningEngine', sub: 'ready frontier steps',       cat: 'executive' },
      { id: 'inhib2',  x: 62,   y: 570, w: 210, label: 'InhibitionController', sub: 'low-confidence veto',  cat: 'executive' },
      { id: 'ideo3',   x: 330,  y: 290, w: 190, label: 'ideomotor.intent', sub: 'afforded abilities only · + args', cat: 'executive' },
      { id: 'prior4',  x: 330,  y: 430, w: 190, label: 'plan.prior', sub: 'top-down bias, never dispatch',  cat: 'executive' },
      { id: 'field3',  x: 604,  y: 220, w: 210, label: 'Affordance field', sub: 'what the situation offers', cat: 'agency' },
      { id: 'sel3',    x: 604,  y: 400, w: 210, label: 'ActionSelector', sub: 'the competition decides',    cat: 'agency' },
      { id: 'delib3',  x: 604,  y: 556, w: 210, label: 'Deliberation facet', sub: 'candidates carry their meaning', cat: 'llm', glow: true },
      { id: 'motor3',  x: 880,  y: 400, w: 200, label: 'Motor → invocation', sub: 'the chosen act goes out', cat: 'agency' },
      { id: 'outc4',   x: 1136, y: 400, w: 180, label: 'Outcome', sub: 'reafference · surprise',            cat: 'agency' },
      { id: 'skill4',  x: 1136, y: 220, w: 180, label: 'Skills & habits', sub: 'abilities get skilled',     cat: 'agency' },
    ],
    edges: [
      { from: 'field3', to: 'abil',   label: 'extractAbilities', fromSide: 't', toSide: 't', via: { x: 440, y: 140 } },
      { from: 'abil',   to: 'actarg' },
      { from: 'actarg', to: 'ideo3' },
      { from: 'ideo3',  to: 'field3', label: 'pre-activate' },
      { from: 'planE',  to: 'prior4' },
      { from: 'prior4', to: 'field3', label: 'bias', fromSide: 'r', toSide: 'b', reach: 10 },
      { from: 'field3', to: 'sel3' },
      { from: 'sel3',   to: 'delib3', label: 'contested · high-stakes', cat: 'llm' },
      { from: 'delib3', to: 'motor3', label: 'chosen intent', cat: 'llm', fromSide: 'r', toSide: 'b', reach: 16 },
      { from: 'sel3',   to: 'motor3' },
      { from: 'inhib2', to: 'sel3',   dash: true, label: 'veto', fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'motor3', to: 'outc4' },
      { from: 'outc4',  to: 'skill4', label: 'learn' },
      { from: 'skill4', to: 'field3', dash: true, label: 'refined priors', fromSide: 't', toSide: 't', ext: 40, at: 0.5 },
      { from: 'outc4',  to: 'planE',  dash: true, label: 'plan advances', fromSide: 'b', toSide: 'b', via: { x: 620, y: 672 } },
    ],
  },

  // ═══ 11 · TRANSPORTS ══════════════════════════════════════
  {
    file: 'transports.svg',
    title: 'Transports — one envelope protocol, three carriers',
    subtitle: 'Outbound projections and inbound stimuli ride the same envelopes; arrival is decoupled from application, so a live socket stays replay-compatible',
    width: 1360, height: 720,
    legend: [ 'infra', 'agency', 'world' ],
    groups: [
      { x: 44,   y: 118, w: 250, h: 410, label: 'outbound — the will projects',  cat: 'infra' },
      { x: 580,  y: 118, w: 250, h: 450, label: 'the carriers',                  cat: 'infra' },
      { x: 866,  y: 118, w: 450, h: 450, label: 'the far side',                  cat: 'world' },
      { x: 44,   y: 560, w: 786, h: 120, label: 'inbound — the world arrives',   cat: 'infra' },
    ],
    nodes: [
      { id: 'outs',    x: 66,   y: 150, w: 206, label: 'Replies & messages', sub: 'reply · message · chunk · activity', cat: 'infra' },
      { id: 'obs',     x: 66,   y: 280, w: 206, label: 'Observability', sub: 'session_log · token_report',  cat: 'infra' },
      { id: 'inv3',    x: 66,   y: 410, w: 206, label: 'Effector invocations', sub: 'the host runs these',  cat: 'agency' },
      { id: 'tctrl',   x: 340,  y: 280, w: 210, label: 'TransportController', sub: 'the tick-loop ⇄ transport boundary', cat: 'infra', glow: true },
      { id: 'loop3',   x: 600,  y: 150, w: 210, label: 'LoopbackTransport', sub: 'in-memory — tests · replay', cat: 'infra' },
      { id: 'sio2',    x: 600,  y: 290, w: 210, label: 'SocketIoTransport', sub: 'production — the Will is the client', cat: 'world' },
      { id: 'strm2',   x: 600,  y: 430, w: 210, label: 'StreamTransport', sub: 'in-process host embedding', cat: 'infra' },
      { id: 'tests2',  x: 886,  y: 150, w: 190, label: 'Tests · replay', sub: 'deterministic far side',     cat: 'world' },
      { id: 'backend3', x: 886, y: 290, w: 190, label: 'Backend / Studio', sub: 'socket.io server · hosted minds', cat: 'world' },
      { id: 'hostp',   x: 886,  y: 430, w: 190, label: 'Host process', sub: 'facade · sidecar consumers',   cat: 'world' },
      { id: 'acks',    x: 1136, y: 290, w: 180, label: 'Acks return', sub: 'delivery · execution',          cat: 'world' },
      { id: 'inq3',    x: 340,  y: 592, w: 210, label: 'InboundQueue', sub: 'arrival ≠ application',        cat: 'infra', glow: true },
      { id: 'applied', x: 66,   y: 592, w: 206, label: 'Applied on-tick', sub: 'FIFO · tick-stamped · replayable', cat: 'infra' },
    ],
    edges: [
      { from: 'outs',   to: 'tctrl' },
      { from: 'obs',    to: 'tctrl',  dash: true },
      { from: 'inv3',   to: 'tctrl' },
      { from: 'tctrl',  to: 'loop3' },
      { from: 'tctrl',  to: 'sio2' },
      { from: 'tctrl',  to: 'strm2' },
      { from: 'loop3',  to: 'tests2' },
      { from: 'sio2',   to: 'backend3' },
      { from: 'strm2',  to: 'hostp' },
      { from: 'backend3', to: 'acks', dash: true },
      { from: 'acks',   to: 'inq3',   dash: true, label: 'inbound_message · percept · ack', fromSide: 'b', toSide: 'r', via: { x: 1000, y: 640 } },
      { from: 'inq3',   to: 'applied' },
    ],
  },

  // ═══ 12 · SIMULATION CORE ═════════════════════════════════
  {
    file: 'simulation-core.svg',
    title: 'The simulation core — where the clock meets the state',
    subtitle: 'One loop drives priority-ordered engines over copy-on-write state; hosts observe through tick listeners — the connection points',
    width: 1360, height: 640,
    legend: [ 'infra', 'memory', 'world' ],
    groups: [
      { x: 44,   y: 118, w: 500, h: 440, label: 'the loop',           cat: 'infra' },
      { x: 574,  y: 118, w: 460, h: 440, label: 'the state',          cat: 'memory' },
      { x: 1064, y: 118, w: 252, h: 440, label: 'connection points',  cat: 'world' },
    ],
    nodes: [
      { id: 'clk',     x: 62,   y: 150, w: 200, label: 'SimulationClock', sub: 'wall interval | fixed Δ',   cat: 'infra' },
      { id: 'sim2',    x: 62,   y: 290, w: 200, label: 'DefaultSimulation', sub: 'start · stop · step(n)',  cat: 'infra', glow: true },
      { id: 'reg3',    x: 62,   y: 430, w: 200, label: 'addEngine()', sub: 'assembly registers 40+',       cat: 'infra' },
      { id: 'ctx4',    x: 330,  y: 150, w: 190, label: 'SimulationContext', sub: 'seeded prng · logical time', cat: 'infra' },
      { id: 'orch4',   x: 330,  y: 290, w: 190, label: 'Orchestrator', sub: 'serial react() by priority',  cat: 'infra' },
      { id: 'frozen2', x: 594,  y: 150, w: 200, label: 'Frozen state view', sub: 'engines read — never write', cat: 'infra' },
      { id: 'cmds4',   x: 594,  y: 290, w: 200, label: 'StateCommands', sub: 'set · delete · metrics',     cat: 'infra' },
      { id: 'statem',  x: 824,  y: 290, w: 190, label: 'StateManager', sub: 'entities · metrics',          cat: 'memory' },
      { id: 'snap4',   x: 824,  y: 430, w: 190, label: 'SnapshotManager', sub: 'copy-on-write · interval', cat: 'memory' },
      { id: 'disk',    x: 594,  y: 430, w: 200, label: 'Persistence', sub: 'disk snapshots (optional)',    cat: 'memory' },
      { id: 'tickl',   x: 1084, y: 290, w: 212, label: 'Tick listeners', sub: 'snapshot · outbox · invocations → host', cat: 'world', glow: true },
      { id: 'restore', x: 1084, y: 430, w: 212, label: 'Restore / replay', sub: 'load a snapshot, resume the life', cat: 'world' },
    ],
    edges: [
      { from: 'clk',    to: 'sim2' },
      { from: 'sim2',   to: 'orch4',  label: 'tick' },
      { from: 'reg3',   to: 'orch4',  dash: true, label: 'priority order' },
      { from: 'ctx4',   to: 'orch4',  dash: true },
      { from: 'orch4',  to: 'cmds4',  label: 'emit' },
      { from: 'frozen2', to: 'orch4', dash: true, label: 'reads', fromSide: 'l', toSide: 't', reach: 8, at: 0.3 },
      { from: 'cmds4',  to: 'statem' },
      { from: 'statem', to: 'frozen2', dash: true, label: 'next tick’s view', fromSide: 't', toSide: 'r', reach: 8 },
      { from: 'statem', to: 'snap4' },
      { from: 'snap4',  to: 'disk',   dash: true },
      { from: 'statem', to: 'tickl',  label: 'per tick' },
      { from: 'snap4',  to: 'restore', dash: true },
    ],
  },

  // ═══ 13 · COGNITIVE WIRING ════════════════════════════════
  {
    file: 'cognitive-wiring.svg',
    title: 'The cognitive layer — how engines talk',
    subtitle: 'Typed attachments for hard wiring, a schema-validated bus for events — queued during the tick, delivered and committed at Phase 2',
    width: 1360, height: 640,
    legend: [ 'executive', 'infra' ],
    groups: [
      { x: 44,   y: 118, w: 500, h: 440, label: 'assembly time — the wiring', cat: 'infra' },
      { x: 574,  y: 118, w: 742, h: 440, label: 'tick time — the traffic',    cat: 'executive' },
    ],
    nodes: [
      { id: 'asm',     x: 62,   y: 150, w: 200, label: 'assembleMind()', sub: 'constructs · wires · registers', cat: 'infra', glow: true },
      { id: 'att',     x: 62,   y: 290, w: 200, label: 'attach*()', sub: 'typed cross-engine wiring',      cat: 'infra' },
      { id: 'prio',    x: 62,   y: 430, w: 200, label: 'Engine priority', sub: 'deterministic tick order', cat: 'infra' },
      { id: 'schreg',  x: 330,  y: 150, w: 190, label: 'Schema registry', sub: 'validated event contracts', cat: 'infra' },
      { id: 'audit2',  x: 330,  y: 430, w: 190, label: 'Assembly audit', sub: 'unwired attach points fail loudly', cat: 'infra' },
      { id: 'eng',     x: 594,  y: 290, w: 220, label: 'A CognitiveEngine', sub: 'react(Δ, tick, frozen, ctx)', cat: 'executive', glow: true },
      { id: 'pub',     x: 594,  y: 150, w: 220, label: 'publishes()', sub: 'declares its event schemas',   cat: 'executive' },
      { id: 'sub2',    x: 594,  y: 430, w: 220, label: 'subscribes()', sub: 'the topics it listens to',    cat: 'executive' },
      { id: 'bus4',    x: 880,  y: 290, w: 200, label: 'CognitiveBus', sub: 'queued — never mid-tick',     cat: 'infra', glow: true },
      { id: 'oncog',   x: 1136, y: 290, w: 180, label: 'onCognitiveEvent()', sub: 'returns StateCommands', cat: 'executive' },
      { id: 'flush2',  x: 880,  y: 150, w: 200, label: 'Phase-2 flush', sub: 'deliver after commit',       cat: 'infra' },
      { id: 'drain2',  x: 1136, y: 150, w: 180, label: 'drainCommands()', sub: 'handler effects commit',   cat: 'infra' },
    ],
    edges: [
      { from: 'asm',    to: 'att' },
      { from: 'asm',    to: 'schreg', dash: true },
      { from: 'att',    to: 'eng',    label: 'hard wiring' },
      { from: 'prio',   to: 'audit2', dash: true },
      { from: 'audit2', to: 'eng',    dash: true, label: 'verified wired', fromSide: 'r', toSide: 'b', reach: 10, at: 0.35 },
      { from: 'eng',    to: 'pub' },
      { from: 'eng',    to: 'sub2' },
      { from: 'pub',    to: 'bus4',   label: 'publish', fromSide: 'r', toSide: 't', reach: 8, at: 0.3 },
      { from: 'sub2',   to: 'bus4',   dash: true, label: 'topic filter', fromSide: 'r', toSide: 'b', reach: 8 },
      { from: 'bus4',   to: 'flush2' },
      { from: 'flush2', to: 'oncog',  label: 'deliver', fromSide: 'r', toSide: 't', reach: 8, at: 0.35 },
      { from: 'oncog',  to: 'drain2', fromSide: 't', toSide: 'b' },
    ],
  },

  // ═══ 14 · LLM CYCLE ═══════════════════════════════════════
  {
    file: 'llm-cycle.svg',
    title: 'One LLM call — compose, route, record, parse',
    subtitle: 'Replay re-feed outranks mock outranks live; every path is recorded; the parser never trusts the model’s formatting',
    width: 1360, height: 720,
    legend: [ 'executive', 'llm', 'infra', 'world' ],
    groups: [
      { x: 44,   y: 118, w: 250, h: 440, label: 'compose',            cat: 'llm' },
      { x: 560,  y: 118, w: 250, h: 570, label: 'route — precedence', cat: 'infra' },
      { x: 840,  y: 118, w: 220, h: 440, label: 'every path recorded', cat: 'infra' },
      { x: 1090, y: 118, w: 226, h: 440, label: 'never trust format', cat: 'executive' },
    ],
    nodes: [
      { id: 'sysp',    x: 66,   y: 150, w: 206, label: 'buildSystemPrompt', sub: 'core preamble · identity · schema', cat: 'llm' },
      { id: 'usrp',    x: 66,   y: 290, w: 206, label: 'buildUserMessage', sub: 'live state → awareness-scoped sections', cat: 'llm' },
      { id: 'focus3',  x: 66,   y: 430, w: 206, label: 'Focus + report', sub: 'what THIS reasoning is about', cat: 'executive' },
      { id: 'dir',     x: 330,  y: 290, w: 190, label: 'LLMDirector', sub: 'per-Will · per-call meta',      cat: 'llm', glow: true },
      { id: 'refeed3', x: 580,  y: 150, w: 210, label: '1 · Re-feed source', sub: 'replay takes precedence', cat: 'infra' },
      { id: 'mock3',   x: 580,  y: 290, w: 210, label: '2 · Mock (testMode)', sub: 'deterministic, zero-key', cat: 'infra' },
      { id: 'live2',   x: 580,  y: 430, w: 210, label: '3 · Live provider', sub: 'anthropic · openai-compatible', cat: 'world' },
      { id: 'gate5',   x: 580,  y: 590, w: 210, label: 'withGate', sub: 'semaphore · 429 backoff',          cat: 'infra' },
      { id: 'rec4',    x: 860,  y: 150, w: 180, label: 'Recorder', sub: 'the replay transcript',            cat: 'infra' },
      { id: 'raw',     x: 860,  y: 290, w: 180, label: 'Raw completion', sub: 'text + token counts',        cat: 'llm' },
      { id: 'tok2',    x: 860,  y: 430, w: 180, label: 'TokenTracker', sub: 'usage · cost per function',    cat: 'infra' },
      { id: 'parse3',  x: 1110, y: 290, w: 186, label: 'parseResponse', sub: 'JSON → balanced → fallback',  cat: 'executive' },
      { id: 'tags2',   x: 1110, y: 150, w: 186, label: 'Tagged blocks', sub: '[PLANS] · [REPLY_TEXT] …',    cat: 'executive' },
      { id: 'out4',    x: 1110, y: 430, w: 186, label: 'Commands & reply', sub: 'state effects · outbox',   cat: 'executive' },
    ],
    edges: [
      { from: 'sysp',   to: 'dir',    fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'usrp',   to: 'dir' },
      { from: 'focus3', to: 'usrp',   dash: true, fromSide: 't', toSide: 'b' },
      { from: 'dir',    to: 'refeed3', label: 'first', cat: 'llm' },
      { from: 'dir',    to: 'mock3',  label: 'then',  cat: 'llm' },
      { from: 'dir',    to: 'live2',  label: 'else',  cat: 'llm' },
      { from: 'live2',  to: 'gate5',  dash: true, label: 'concurrency' },
      { from: 'refeed3', to: 'raw',   fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'mock3',  to: 'raw' },
      { from: 'live2',  to: 'raw',    fromSide: 'r', toSide: 'b', reach: 8 },
      { from: 'raw',    to: 'rec4',   dash: true, label: 'record' },
      { from: 'raw',    to: 'tok2',   dash: true },
      { from: 'raw',    to: 'parse3' },
      { from: 'parse3', to: 'tags2' },
      { from: 'parse3', to: 'out4' },
      { from: 'tags2',  to: 'out4',   dash: true, fromSide: 'r', toSide: 'r', ext: 26 },
    ],
  },

  // ═══ 15 · HOST SURFACES ═══════════════════════════════════
  {
    file: 'host-surfaces.svg',
    title: 'The edge — four doors into one body',
    subtitle: 'One env-configured boot raises the same mind for every surface; every door speaks the subject paradigm and persists through the same artifact',
    width: 1360, height: 660,
    legend: [ 'world', 'infra', 'agency', 'memory' ],
    groups: [
      { x: 44,   y: 118, w: 500, h: 460, label: 'one boot',           cat: 'infra' },
      { x: 574,  y: 118, w: 460, h: 460, label: 'the doors',          cat: 'world' },
      { x: 1064, y: 118, w: 252, h: 460, label: 'one body',           cat: 'infra' },
    ],
    nodes: [
      { id: 'cli2',    x: 62,   y: 220, w: 200, label: 'will CLI', sub: 'dispatch: mcp | serve',            cat: 'infra', glow: true },
      { id: 'boot2',   x: 330,  y: 220, w: 190, label: 'host/boot.ts', sub: 'env → wake | create',          cat: 'infra' },
      { id: 'pmaf',    x: 330,  y: 400, w: 190, label: 'PMA artifact', sub: 'the self between sessions',    cat: 'memory', glow: true },
      { id: 'mcps',    x: 594,  y: 150, w: 200, label: 'MCP server', sub: 'perceive · next_utterance · state · save', cat: 'world' },
      { id: 'https',   x: 594,  y: 290, w: 200, label: 'HTTP sidecar', sub: 'routes + SSE /utterances',     cat: 'world' },
      { id: 'sdk',     x: 594,  y: 430, w: 200, label: 'Will facade (SDK)', sub: 'projections · effectors · save', cat: 'infra' },
      { id: 'tap2',    x: 864,  y: 220, w: 190, label: 'UtteranceTap', sub: 'no reply lost between calls',  cat: 'infra' },
      { id: 'bridge2', x: 864,  y: 430, w: 190, label: 'connectMcpEffectors', sub: 'external tools → abilities', cat: 'agency' },
      { id: 'stem3',   x: 1084, y: 290, w: 212, label: 'WillStem', sub: 'one body under all doors',         cat: 'infra', glow: true },
    ],
    edges: [
      { from: 'cli2',   to: 'boot2' },
      { from: 'boot2',  to: 'mcps',   label: 'will mcp', at: 0.35 },
      { from: 'boot2',  to: 'https',  label: 'will serve', at: 0.35 },
      { from: 'boot2',  to: 'sdk',    dash: true, fromSide: 'b', toSide: 'l', reach: 16 },
      { from: 'boot2',  to: 'pmaf',   dash: true, label: 'hibernate ⇄ wake' },
      { from: 'boot2',  to: 'bridge2', dash: true, label: 'WILL_MCP_SERVERS', fromSide: 'b', toSide: 'b', via: { x: 700, y: 620 } },
      { from: 'mcps',   to: 'tap2' },
      { from: 'https',  to: 'tap2' },
      { from: 'mcps',   to: 'sdk',    dash: true, fromSide: 'l', toSide: 'l', ext: 26 },
      { from: 'https',  to: 'sdk',    dash: true, fromSide: 'l', toSide: 'l', ext: 12 },
      { from: 'bridge2', to: 'sdk',   label: 'effector', fromSide: 'l', toSide: 'r' },
      { from: 'sdk',    to: 'stem3',  fromSide: 'r', toSide: 'b', reach: 20 },
      { from: 'tap2',   to: 'stem3',  dash: true, fromSide: 'r', toSide: 't', reach: 10 },
    ],
  },

  // ═══ 16 · STEM TRACTS ═════════════════════════════════════
  {
    file: 'stem-tracts.svg',
    title: 'WillStem — the body’s organs (tracts)',
    subtitle: 'The stem stays thin; each tract owns one boundary of the body — intake, outflow, lifecycle, observability — around the same tick loop',
    width: 1360, height: 760,
    legend: [ 'perceptual', 'agency', 'memory', 'infra', 'regulatory', 'meta' ],
    groups: [
      { x: 44,   y: 118, w: 260, h: 300, label: 'intake',        cat: 'perceptual' },
      { x: 44,   y: 448, w: 260, h: 260, label: 'lifecycle',     cat: 'memory' },
      { x: 1046, y: 118, w: 270, h: 480, label: 'outflow',       cat: 'agency' },
      { x: 334,  y: 560, w: 682, h: 148, label: 'observability', cat: 'meta' },
    ],
    nodes: [
      { id: 'stem4',   x: 560,  y: 300, w: 240, label: 'WillStem', sub: 'thin coordinator — tracts own the machinery', cat: 'infra', glow: true },
      { id: 'sensc',   x: 62,   y: 150, w: 220, label: 'SensoryController', sub: 'ingest → senses · chunk streams out', cat: 'perceptual' },
      { id: 'inq4',    x: 62,   y: 290, w: 220, label: 'InboundQueue', sub: 'arrival ≠ application — tick-stamped', cat: 'infra' },
      { id: 'pmac',    x: 62,   y: 480, w: 220, label: 'PMAController', sub: 'distill · load · fidelity eval', cat: 'memory' },
      { id: 'repc',    x: 62,   y: 620, w: 220, label: 'ReplayController', sub: 'record a life · re-run it',   cat: 'infra' },
      { id: 'tctrl2',  x: 560,  y: 150, w: 240, label: 'TransportController', sub: 'envelopes ⇄ the far side', cat: 'infra' },
      { id: 'outw2',   x: 1066, y: 150, w: 230, label: 'OutboxWriter', sub: 'canonical reply rows',            cat: 'infra' },
      { id: 'outc5',   x: 1066, y: 270, w: 230, label: 'OutboxController', sub: 'drain · delivery acks',       cat: 'infra' },
      { id: 'ackr',    x: 1066, y: 390, w: 230, label: 'AckReconciler', sub: 'idempotent — dual ack paths dedup', cat: 'infra' },
      { id: 'effc2',   x: 1066, y: 510, w: 230, label: 'EffectorController', sub: 'invocations · execution acks', cat: 'agency' },
      { id: 'sessl',   x: 354,  y: 620, w: 200, label: 'SessionLogger', sub: 'JSONL cognitive trace',          cat: 'infra' },
      { id: 'health2', x: 584,  y: 620, w: 200, label: 'HealthReporter', sub: 'composite vitals',              cat: 'regulatory' },
      { id: 'bio2',    x: 814,  y: 620, w: 200, label: 'BiographyWriter', sub: 'the life, written to disk',    cat: 'meta' },
    ],
    edges: [
      { from: 'sensc',  to: 'stem4',  label: 'percepts', fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'inq4',   to: 'stem4',  label: 'on-tick' },
      { from: 'tctrl2', to: 'inq4',   dash: true, label: 'inbound envelopes', fromSide: 'l', toSide: 't', reach: 20, at: 0.25 },
      { from: 'stem4',  to: 'tctrl2', dash: true, label: 'outbound' },
      { from: 'stem4',  to: 'outw2',  fromSide: 't', toSide: 'l', reach: 12, label: 'replies' },
      { from: 'outw2',  to: 'outc5' },
      { from: 'outc5',  to: 'ackr',   dash: true },
      { from: 'stem4',  to: 'effc2',  label: 'invocations', fromSide: 'r', toSide: 'l', reach: 10 },
      { from: 'effc2',  to: 'ackr',   dash: true, label: 'acks', fromSide: 't', toSide: 'b' },
      { from: 'pmac',   to: 'stem4',  dash: true, label: 'distill ⇄ load', fromSide: 'r', toSide: 'b', reach: 16 },
      { from: 'repc',   to: 'stem4',  dash: true, fromSide: 'r', toSide: 'b', via: { x: 480, y: 520 } },
      { from: 'stem4',  to: 'sessl',  dash: true, fromSide: 'b', toSide: 't', reach: 8 },
      { from: 'stem4',  to: 'health2', dash: true },
      { from: 'stem4',  to: 'bio2',   dash: true, fromSide: 'b', toSide: 't', reach: 8 },
    ],
  },

  // ═══ 17 · PLANNING & GOALS ════════════════════════════════
  {
    file: 'planning-goals.svg',
    title: 'Plans as priors — goals, frontiers, supervision',
    subtitle: 'Goals form from identity, instruction and curiosity; a plan never dispatches its steps — its ready frontier biases the competition, and outcomes advance it',
    width: 1360, height: 720,
    legend: [ 'executive', 'agency', 'social', 'meta' ],
    groups: [
      { x: 44,   y: 118, w: 250, h: 520, label: 'where goals come from', cat: 'executive' },
      { x: 314,  y: 118, w: 246, h: 540, label: 'the plan lifecycle',    cat: 'executive' },
      { x: 584,  y: 118, w: 246, h: 340, label: 'the frontier',          cat: 'executive' },
      { x: 854,  y: 118, w: 462, h: 540, label: 'execution as bias',     cat: 'agency' },
    ],
    nodes: [
      { id: 'goalm',   x: 66,   y: 150, w: 206, label: 'GoalManager', sub: 'priority · progress · lifecycle', cat: 'executive', glow: true },
      { id: 'gsrc1',   x: 66,   y: 290, w: 206, label: 'Executive newGoals', sub: 'identity-driven formation', cat: 'executive' },
      { id: 'gsrc2',   x: 66,   y: 402, w: 206, label: 'InstructionIntake', sub: 'host instructions → own goals', cat: 'agency' },
      { id: 'gsrc3',   x: 66,   y: 514, w: 206, label: 'Curiosity to resolve', sub: 'familiar yet unidentified people', cat: 'social' },
      { id: 'planE2',  x: 330,  y: 190, w: 214, label: 'PlanningEngine', sub: 'draft · validate · execute · revise', cat: 'executive' },
      { id: 'store2',  x: 330,  y: 350, w: 214, label: 'PlanStore', sub: 'multiple plans per goal · GC',   cat: 'executive' },
      { id: 'superv3', x: 330,  y: 560, w: 214, label: 'PlanSupervisor', sub: 'the judgment faculty',      cat: 'meta' },
      { id: 'front',   x: 600,  y: 190, w: 214, label: 'plan.frontier', sub: 'prerequisite DAG → ready set', cat: 'executive' },
      { id: 'prior5',  x: 600,  y: 350, w: 214, label: 'plan.prior entities', sub: 'one per ready step — a lift', cat: 'executive' },
      { id: 'field4',  x: 870,  y: 350, w: 200, label: 'Affordance competition', sub: 'biased — never bypassed', cat: 'agency' },
      { id: 'enact3',  x: 870,  y: 520, w: 200, label: 'Enacted step', sub: 'motor → world → reafference', cat: 'agency' },
      { id: 'outc7',   x: 1126, y: 520, w: 184, label: 'plan.step.outcome', sub: 'success · quality · surprise', cat: 'agency' },
      { id: 'adv',     x: 1126, y: 350, w: 184, label: 'Frontier advances', sub: 'or replans · or waits',   cat: 'executive' },
      { id: 'prog',    x: 1126, y: 190, w: 184, label: 'Goal progress', sub: 'steps roll up · completion',  cat: 'executive' },
    ],
    edges: [
      { from: 'gsrc1',  to: 'goalm' },
      { from: 'gsrc2',  to: 'goalm',  fromSide: 'r', toSide: 'r', ext: 18 },
      { from: 'gsrc3',  to: 'goalm',  fromSide: 'r', toSide: 'r', ext: 32 },
      { from: 'goalm',  to: 'planE2' },
      { from: 'planE2', to: 'store2' },
      { from: 'store2', to: 'superv3', label: 'assess' },
      { from: 'superv3', to: 'planE2', dash: true, label: 'verdicts', fromSide: 'r', toSide: 'r', ext: 30, at: 0.3 },
      { from: 'planE2', to: 'front' },
      { from: 'front',  to: 'prior5', label: 'ready steps' },
      { from: 'prior5', to: 'field4' },
      { from: 'field4', to: 'enact3', label: 'if the prior wins' },
      { from: 'enact3', to: 'outc7' },
      { from: 'outc7',  to: 'adv',    dash: true, label: 'step done' },
      { from: 'adv',    to: 'front',  dash: true, label: 'next ready set', fromSide: 't', toSide: 't', ext: 30, at: 0.5 },
      { from: 'adv',    to: 'prog' },
      { from: 'prog',   to: 'goalm',  dash: true, label: 'progress → completion', fromSide: 'l', toSide: 'l', via: { x: 700, y: 104 } },
    ],
  },

  // ═══ 18 · SOCIAL COGNITION ════════════════════════════════
  {
    file: 'social-cognition.svg',
    title: 'Knowing others — dossiers, models, bonds',
    subtitle: 'Every referent earns a dossier; recognition fuses the same person and never conflates strangers; the models join into thought, attention and outreach',
    width: 1360, height: 700,
    legend: [ 'social', 'affective', 'executive', 'llm', 'agency' ],
    groups: [
      { x: 44,   y: 118, w: 250, h: 400, label: 'inputs',                cat: 'perceptual' },
      { x: 314,  y: 118, w: 246, h: 480, label: 'the dossier (keid)',    cat: 'social' },
      { x: 594,  y: 118, w: 236, h: 480, label: 'modeling them',         cat: 'social' },
      { x: 860,  y: 118, w: 456, h: 540, label: 'into thought & action', cat: 'executive' },
    ],
    nodes: [
      { id: 'sperc',   x: 66,   y: 150, w: 206, label: 'Social percepts', sub: 'speech · presence · acts',  cat: 'perceptual' },
      { id: 'clearn',  x: 66,   y: 430, w: 206, label: 'Conscious learning', sub: 'executive knownEntityUpdates', cat: 'executive' },
      { id: 'ket2',    x: 330,  y: 190, w: 214, label: 'KnownEntityTracker', sub: 'dossier owner — the single writer', cat: 'social', glow: true },
      { id: 'doss',    x: 330,  y: 350, w: 214, label: 'ke-<keid> dossier', sub: 'name · familiarity · valence · resolution', cat: 'social' },
      { id: 'recog',   x: 330,  y: 520, w: 214, label: 'Recognition (fusion)', sub: 'alias keids — never conflate strangers', cat: 'social' },
      { id: 'tom2',    x: 610,  y: 150, w: 204, label: 'TheoryOfMind', sub: 'what they want · feel',        cat: 'social' },
      { id: 'rep2',    x: 610,  y: 270, w: 204, label: 'ReputationTracker', sub: 'trust · reliability',     cat: 'social' },
      { id: 'bond2',   x: 610,  y: 390, w: 204, label: 'AttachmentEvaluator', sub: 'bonds · closeness',     cat: 'affective' },
      { id: 'emp2',    x: 610,  y: 510, w: 204, label: 'EmpathySimulator', sub: 'their state, felt',        cat: 'social' },
      { id: 'people',  x: 890,  y: 270, w: 200, label: 'People You Know', sub: 'joined per keid → the prompt', cat: 'llm', glow: true },
      { id: 'csal',    x: 890,  y: 430, w: 200, label: 'Conversation salience', sub: 'closeness weights attention', cat: 'perceptual' },
      { id: 'curio',   x: 890,  y: 580, w: 200, label: 'Curiosity goals', sub: 'the pull to resolve someone', cat: 'executive' },
      { id: 'reach4',  x: 1146, y: 430, w: 164, label: 'reach-out', sub: 'binds every known person',        cat: 'agency' },
      { id: 'pma6',    x: 1146, y: 150, w: 164, label: 'PMA', sub: 'bonds · dossiers travel',               cat: 'memory' },
    ],
    edges: [
      { from: 'sperc',  to: 'ket2',   label: 'per referent' },
      { from: 'clearn', to: 'ket2',   label: 'name · facts', fromSide: 'r', toSide: 'l', at: 0.55 },
      { from: 'ket2',   to: 'doss' },
      { from: 'doss',   to: 'recog',  dash: true, label: 'same name?' },
      { from: 'recog',  to: 'doss',   dash: true, label: 'alias → canonical', fromSide: 'l', toSide: 'l', ext: 26 },
      { from: 'doss',   to: 'tom2',   dash: true, fromSide: 't', toSide: 'l', reach: 8 },
      { from: 'doss',   to: 'rep2',   dash: true },
      { from: 'doss',   to: 'bond2',  dash: true },
      { from: 'tom2',   to: 'people', fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'rep2',   to: 'people' },
      { from: 'bond2',  to: 'people', fromSide: 'r', toSide: 'b', reach: 8 },
      { from: 'emp2',   to: 'people', dash: true, via: { x: 862, y: 385 } },
      { from: 'bond2',  to: 'csal' },
      { from: 'recog',  to: 'curio',  dash: true, label: 'familiar yet unresolved', via: { x: 700, y: 628 } },
      { from: 'csal',   to: 'reach4' },
      { from: 'rep2',   to: 'pma6',   dash: true, label: 'travels', fromSide: 't', toSide: 'l', via: { x: 1000, y: 180 } },
    ],
  },

  // ═══ 19 · PROACTIVE COMMUNICATION ═════════════════════════
  {
    file: 'proactive-communication.svg',
    title: 'When the Will speaks first',
    subtitle: 'Drives pull, goals point, imagination pre-activates — and if reaching out wins the competition, the same self authors the words. Losing is normal: unprompted speech is a choice, not a schedule',
    width: 1360, height: 660,
    legend: [ 'affective', 'executive', 'agency', 'llm', 'infra', 'world' ],
    groups: [
      { x: 44,   y: 118, w: 250, h: 420, label: 'the pull',         cat: 'affective' },
      { x: 314,  y: 118, w: 516, h: 420, label: 'the decision',     cat: 'agency' },
      { x: 860,  y: 118, w: 456, h: 420, label: 'the words go out', cat: 'llm' },
    ],
    nodes: [
      { id: 'drv',     x: 66,   y: 150, w: 206, label: 'Social drive · bonds', sub: 'loneliness pulls, closeness invites', cat: 'affective' },
      { id: 'gtar',    x: 66,   y: 290, w: 206, label: 'Goal-directed outreach', sub: 'an active goal targets someone', cat: 'executive' },
      { id: 'imag',    x: 66,   y: 430, w: 206, label: 'The executive imagines it', sub: 'communicate action → ideomotor', cat: 'executive' },
      { id: 'reach5',  x: 340,  y: 290, w: 200, label: 'reach-out affordance', sub: 'bound to a known person',  cat: 'agency' },
      { id: 'comp5',   x: 610,  y: 290, w: 200, label: 'The competition', sub: 'may lose — silence is normal', cat: 'agency', glow: true },
      { id: 'motor5',  x: 610,  y: 450, w: 200, label: 'Motor — communicate', sub: 'authorOutreach(entity, gist)', cat: 'agency' },
      { id: 'author',  x: 880,  y: 450, w: 210, label: 'Outreach authoring facet', sub: 'the SAME self writes the words', cat: 'llm', glow: true },
      { id: 'guard2',  x: 880,  y: 290, w: 210, label: 'Bounded authoring', sub: 'timeout · one turn per entity', cat: 'infra' },
      { id: 'writer3', x: 1146, y: 450, w: 164, label: 'OutboxWriter', sub: 'bubbles · thread',                cat: 'infra' },
      { id: 'deliver', x: 1146, y: 290, w: 164, label: 'Host delivery', sub: 'unprompted — by design',         cat: 'world' },
    ],
    edges: [
      { from: 'drv',    to: 'reach5', label: 'drive urgency', fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'gtar',   to: 'reach5' },
      { from: 'imag',   to: 'reach5', label: 'pre-activate', fromSide: 'r', toSide: 'b', reach: 8 },
      { from: 'reach5', to: 'comp5' },
      { from: 'comp5',  to: 'motor5', label: 'wins' },
      { from: 'motor5', to: 'author' },
      { from: 'guard2', to: 'author', dash: true },
      { from: 'author', to: 'writer3' },
      { from: 'writer3', to: 'deliver' },
    ],
  },

  // ═══ 20 · COMPETENCE ══════════════════════════════════════
  {
    file: 'competence.svg',
    title: 'Competence — from act to habit to skill',
    subtitle: 'Every enaction predicts its own outcome; surprise drives the learning rule — value, habit and param priors accrue, sequences chunk into new abilities, and it all travels in the PMA',
    width: 1360, height: 720,
    legend: [ 'agency', 'world', 'memory' ],
    groups: [
      { x: 314,  y: 118, w: 246, h: 400, label: 'prediction vs reality', cat: 'agency' },
      { x: 584,  y: 118, w: 512, h: 290, label: 'the learning rule',     cat: 'agency' },
      { x: 1110, y: 118, w: 206, h: 560, label: 'what accrues',          cat: 'agency' },
      { x: 44,   y: 548, w: 516, h: 130, label: 'the growing repertoire', cat: 'agency' },
    ],
    nodes: [
      { id: 'fold2',   x: 66,   y: 150, w: 200, label: 'PMA competence fold', sub: 'travels · restores on wake', cat: 'memory' },
      { id: 'act4',    x: 66,   y: 290, w: 200, label: 'An enacted schema', sub: 'params bound from the situation', cat: 'agency' },
      { id: 'eff4',    x: 336,  y: 150, w: 200, label: 'Efference copy', sub: 'predicted reward · valence — BEFORE', cat: 'agency' },
      { id: 'outc8',   x: 336,  y: 430, w: 200, label: 'Observed outcome', sub: 'success · quality — the host ack', cat: 'world' },
      { id: 'surp',    x: 610,  y: 290, w: 190, label: 'Surprise', sub: '|predicted − actual|',           cat: 'agency' },
      { id: 'rule',    x: 870,  y: 290, w: 200, label: 'recordOutcome()', sub: 'the proceduralization curve', cat: 'agency', glow: true },
      { id: 'val',     x: 1126, y: 150, w: 174, label: 'valueEstimate', sub: 'EMA toward quality',         cat: 'agency' },
      { id: 'hab',     x: 1126, y: 290, w: 174, label: 'habitStrength', sub: 'grows only on confident success', cat: 'agency' },
      { id: 'ppr',     x: 1126, y: 430, w: 174, label: 'paramPriors', sub: 'known-good args become defaults', cat: 'agency' },
      { id: 'proc2',   x: 1126, y: 600, w: 174, label: 'Proceduralized', sub: 'habit ≥ 0.6 — System 1 owns it', cat: 'agency' },
      { id: 'comp6',   x: 336,  y: 590, w: 200, label: 'Composites', sub: 'chunked sequences — NEW abilities', cat: 'agency' },
      { id: 'rep6',    x: 66,   y: 590, w: 200, label: 'SchemaRepertoire', sub: 'innate + external + learned', cat: 'agency' },
    ],
    edges: [
      { from: 'act4',   to: 'eff4',   label: 'before' },
      { from: 'act4',   to: 'outc8',  label: 'after' },
      { from: 'eff4',   to: 'surp' },
      { from: 'outc8',  to: 'surp' },
      { from: 'surp',   to: 'rule' },
      { from: 'rule',   to: 'val',    fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'rule',   to: 'hab' },
      { from: 'rule',   to: 'ppr',    fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'hab',    to: 'proc2',  dash: true, fromSide: 'r', toSide: 'r', via: { x: 1338, y: 472 } },
      { from: 'proc2',  to: 'comp6',  label: 'chunk', fromSide: 'l', toSide: 'r' },
      { from: 'comp6',  to: 'rep6' },
      { from: 'rep6',   to: 'fold2',  dash: true, fromSide: 'l', toSide: 'l', ext: 26 },
      { from: 'rep6',   to: 'act4',   dash: true, label: 'affords next time' },
    ],
  },

  // ═══ 21 · PERSONA CHANNELS ════════════════════════════════
  {
    file: 'persona-channels.svg',
    title: 'Two channels of character — Channel A & Channel B',
    subtitle: 'One prior, developed from lived behavior. Channel A tunes the machinery continuously (subconscious); Channel B surfaces coarse trait bands into the prompt (self-knowledge) — and behavior feeds the loop again',
    width: 1360, height: 740,
    legend: [ 'meta', 'regulatory', 'executive', 'llm', 'agency' ],
    groups: [
      { x: 44,   y: 118, w: 250, h: 510, label: 'lived evidence',                     cat: 'meta' },
      { x: 314,  y: 118, w: 246, h: 410, label: 'the write-back',                     cat: 'meta' },
      { x: 584,  y: 118, w: 506, h: 250, label: 'Channel A — continuous · subconscious', cat: 'regulatory' },
      { x: 584,  y: 400, w: 506, h: 250, label: 'Channel B — banded · self-known',    cat: 'llm' },
      { x: 1104, y: 118, w: 222, h: 470, label: 'dual process',                       cat: 'infra' },
    ],
    nodes: [
      { id: 'traits',  x: 66,   y: 190, w: 206, label: 'Self-model traits', sub: 'formed from own behavior',  cat: 'meta' },
      { id: 'msig',    x: 66,   y: 330, w: 206, label: 'Meta signals', sub: 'bias · calibration · insight',   cat: 'meta' },
      { id: 'behav',   x: 66,   y: 520, w: 206, label: 'Demonstrated behavior', sub: 'what the Will actually does', cat: 'agency' },
      { id: 'consol',  x: 330,  y: 260, w: 214, label: 'PersonaConsolidator', sub: 'bounded · decaying — base never mutates', cat: 'meta', glow: true },
      { id: 'prior6',  x: 330,  y: 430, w: 214, label: 'persona-prior entity', sub: 'durable — travels in the PMA', cat: 'memory' },
      { id: 'effcfg',  x: 600,  y: 210, w: 200, label: 'base ⊕ prior', sub: 'read LIVE, every tick',          cat: 'regulatory' },
      { id: 'engs',    x: 870,  y: 150, w: 200, label: 'Engine dispositions', sub: 'threat · curiosity · plan bias…', cat: 'regulatory' },
      { id: 'gate5',   x: 870,  y: 282, w: 200, label: 'Effort gate', sub: 'when to recruit the deliberate self', cat: 'executive' },
      { id: 'bands',   x: 600,  y: 440, w: 200, label: 'Trait bands', sub: 'coarse on purpose — cache-stable', cat: 'llm' },
      { id: 'surf',    x: 870,  y: 440, w: 200, label: 'Prompt surfacing', sub: '“markedly conscientious”',   cat: 'llm' },
      { id: 'ctxb',    x: 600,  y: 560, w: 200, label: 'Context naming', sub: 'plan links named to the facet', cat: 'llm' },
      { id: 'sys1',    x: 1120, y: 210, w: 190, label: 'System 1', sub: 'the deterministic machinery',        cat: 'agency' },
      { id: 'sys2',    x: 1120, y: 480, w: 190, label: 'System 2', sub: 'the deliberate self — one call',     cat: 'llm' },
    ],
    edges: [
      { from: 'behav',  to: 'traits', dash: true, fromSide: 'l', toSide: 'l', ext: 16 },
      { from: 'behav',  to: 'msig',   dash: true },
      { from: 'traits', to: 'consol' },
      { from: 'msig',   to: 'consol' },
      { from: 'consol', to: 'prior6', label: 'bounded deltas' },
      { from: 'prior6', to: 'effcfg', label: '⊕', fromSide: 'r', toSide: 'l' },
      { from: 'traits', to: 'bands',  dash: true, label: 'trait values', via: { x: 560, y: 380 } },
      { from: 'effcfg', to: 'engs' },
      { from: 'effcfg', to: 'gate5' },
      { from: 'engs',   to: 'sys1' },
      { from: 'gate5',  to: 'sys2',   dash: true, label: 'recruits', fromSide: 'r', toSide: 't' },
      { from: 'bands',  to: 'surf' },
      { from: 'surf',   to: 'sys2' },
      { from: 'ctxb',   to: 'sys2',   dash: true, fromSide: 'r', toSide: 'b' },
      { from: 'sys2',   to: 'behav',  dash: true, label: 'behavior — from either system — demonstrates the traits', fromSide: 'b', toSide: 'b', via: { x: 700, y: 700 } },
    ],
  },

  // ═══ 22 · EXAFFERENCE ═════════════════════════════════════
  {
    file: 'exafference-loop.svg',
    title: 'Exafference — telling the world apart from our own echo',
    subtitle: 'Every enaction predicts its sensory footprint; corollary discharge splits afference — the echo is attenuated and can never rupture; the world softens engagement, revokes commitment, confirms un-acked actions',
    width: 1360, height: 780,
    legend: [ 'agency', 'world', 'perceptual', 'llm' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 332, label: 'act — the efference side',  cat: 'agency' },
      { x: 300,  y: 118, w: 236, h: 512, label: 'the world',                 cat: 'world' },
      { x: 556,  y: 118, w: 250, h: 332, label: 'perceive · split',          cat: 'perceptual' },
      { x: 826,  y: 118, w: 250, h: 562, label: 'the two afferences',        cat: 'perceptual' },
      { x: 1096, y: 118, w: 224, h: 632, label: 'respond · learn',           cat: 'agency' },
    ],
    nodes: [
      { id: 'motor',    x: 62,   y: 150, w: 200, label: 'MotorSchemaExecutor', sub: 'enacts · emits efference copy',    cat: 'agency' },
      { id: 'conseq',   x: 62,   y: 300, w: 200, label: 'Consequence descriptor', sub: 'sensory footprint · TTL 30t',  cat: 'agency' },
      { id: 'host',     x: 318,  y: 150, w: 200, label: 'Host / channel',    sub: 'runs it · delivers it',             cat: 'world' },
      { id: 'echo',     x: 318,  y: 390, w: 200, label: 'Echo of our action', sub: 'quote-back · channel echo',        cat: 'world' },
      { id: 'event',    x: 318,  y: 540, w: 200, label: 'Genuine world event', sub: 'unprompted change',               cat: 'world' },
      { id: 'extero',   x: 576,  y: 150, w: 210, label: 'Exteroception',     sub: 'entity changes → percepts',         cat: 'perceptual' },
      { id: 'matcher',  x: 576,  y: 300, w: 210, label: 'Corollary discharge', sub: 'FNV-1a hash + containment',       cat: 'perceptual' },
      { id: 'reaffP',   x: 846,  y: 150, w: 210, label: 'Reafferent percept', sub: 'ours — salience × 0.25 · intent id', cat: 'perceptual' },
      { id: 'exaffP',   x: 846,  y: 330, w: 210, label: 'Exafferent percept', sub: 'the world — full salience',        cat: 'perceptual' },
      { id: 'rupture',  x: 846,  y: 510, w: 210, label: 'Rupture',           sub: 'gate 0.4 · erodes situation.stability', cat: 'agency' },
      { id: 'reaffE',   x: 1112, y: 150, w: 192, label: 'ReafferenceEngine', sub: 'soft outcome 0.6 · frees intent',   cat: 'agency' },
      { id: 'selector', x: 1112, y: 330, w: 192, label: 'ActionSelector',    sub: 'switch-cost × (1 − rupture)',       cat: 'agency' },
      { id: 'revoke',   x: 1112, y: 470, w: 192, label: 'Revocation tombstone', sub: 'rupture ≥ 0.7 — lets go, no successor', cat: 'agency' },
      { id: 'delib',    x: 1112, y: 610, w: 192, label: 'DeliberationEngine', sub: 'drops revoked · voices revokedBy', cat: 'llm', glow: true },
    ],
    edges: [
      { from: 'motor',   to: 'host' },
      { from: 'motor',   to: 'conseq',   dash: true, label: 'expected footprint', fromSide: 'b', toSide: 't' },
      { from: 'host',    to: 'echo',     fromSide: 'b', toSide: 't' },
      { from: 'echo',    to: 'extero' },
      { from: 'event',   to: 'extero',   at: 0.3 },
      { from: 'conseq',  to: 'matcher',  dash: true, label: 'live descriptors' },
      { from: 'extero',  to: 'matcher',  label: 'per-percept matchText', fromSide: 'b', toSide: 't' },
      { from: 'matcher', to: 'reaffP',   label: 'match — it was me' },
      { from: 'matcher', to: 'exaffP',   label: 'miss', at: 0.5 },
      { from: 'reaffP',  to: 'reaffE' },
      { from: 'exaffP',  to: 'rupture',  label: 'salience above gate', fromSide: 'b', toSide: 't' },
      { from: 'rupture', to: 'selector', label: 'soften engagement' },
      { from: 'rupture', to: 'revoke' },
      { from: 'revoke',  to: 'delib',    label: 'honored next tick', fromSide: 'b', toSide: 't' },
    ],
  },

  // ═══ 23 · POLICY REAFFERENCE ══════════════════════════════
  {
    file: 'policy-reafference-loop.svg',
    title: 'Policy reafference — the mind learns may from can',
    subtitle: 'A boundary felt as world resistance: a PDP judges each reach; refusal teaches availability (never competence), a class “never” lets go of a deliberation, escalate holds and asks — and replay re-feeds recorded verdicts',
    width: 1360, height: 820,
    legend: [ 'agency', 'infra', 'world' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 332, label: 'act — the mind reaches',      cat: 'agency' },
      { x: 300,  y: 118, w: 236, h: 462, label: 'the boundary (stem)',         cat: 'infra' },
      { x: 556,  y: 118, w: 250, h: 632, label: 'three fates',                 cat: 'infra' },
      { x: 826,  y: 118, w: 250, h: 512, label: 'reafference — may from can',  cat: 'agency' },
      { x: 1096, y: 118, w: 224, h: 512, label: 'the field re-forms',          cat: 'agency' },
    ],
    nodes: [
      { id: 'motor',  x: 62,   y: 150, w: 200, label: 'MotorSchemaExecutor',  sub: 'external schema → awaiting',            cat: 'agency' },
      { id: 'invok',  x: 62,   y: 300, w: 200, label: 'agency.invocation',    sub: 'schema · params · intent id',           cat: 'agency' },
      { id: 'pep',    x: 318,  y: 150, w: 200, label: 'effectorController — PEP', sub: 'the one tract every effect crosses', cat: 'infra' },
      { id: 'pdp',    x: 318,  y: 300, w: 200, label: 'PolicyArbiter — PDP',  sub: 'rule table · HELM · any provider',      cat: 'infra' },
      { id: 'tape',   x: 318,  y: 470, w: 200, label: 'Verdict tape',         sub: 'recorded — replay re-feeds, never re-asks', cat: 'infra' },
      { id: 'allow',  x: 576,  y: 150, w: 210, label: 'ALLOW → the world',    sub: 'dispatched · the host acks',            cat: 'world' },
      { id: 'deny',   x: 576,  y: 330, w: 210, label: 'DENY → refusal ack',   sub: 'host-rejection-shaped · next boundary', cat: 'infra' },
      { id: 'esc',    x: 576,  y: 510, w: 210, label: 'ESCALATE → held',      sub: 'clock stopped · TTL 30 ticks',          cat: 'infra' },
      { id: 'ask',    x: 576,  y: 660, w: 210, label: 'The ask — voiced once', sub: 'first person · resolve or expire',     cat: 'infra', glow: true },
      { id: 'reaff',  x: 846,  y: 150, w: 210, label: 'ReafferenceEngine',    sub: 'refused ≠ failed — routed apart',       cat: 'agency' },
      { id: 'avail',  x: 846,  y: 330, w: 210, label: 'Availability — may',   sub: 'class cuts · instance dents · recovers', cat: 'agency' },
      { id: 'skill',  x: 846,  y: 510, w: 210, label: 'LearnedSkill — can',   sub: 'untouched by refusals',                 cat: 'agency' },
      { id: 'synth',  x: 1112, y: 150, w: 192, label: 'AffordanceSynthesizer', sub: 'damps by availability — re-probe lives', cat: 'agency' },
      { id: 'select', x: 1112, y: 330, w: 192, label: 'ActionSelector',       sub: 'class refusal while deliberating →',    cat: 'agency' },
      { id: 'revoke', x: 1112, y: 510, w: 192, label: 'Revocation tombstone', sub: 'lets go — no successor',                cat: 'agency' },
    ],
    edges: [
      { from: 'motor',  to: 'invok',  dash: true, label: 'holds awaiting · emits' },
      { from: 'invok',  to: 'pep' },
      { from: 'pep',    to: 'pdp',    label: 'evaluate' },
      { from: 'pdp',    to: 'tape',   dash: true, label: 'every verdict' },
      { from: 'pdp',    to: 'allow',  label: 'allow',    fromSide: 'r', toSide: 'l' },
      { from: 'pdp',    to: 'deny',   label: 'deny',     fromSide: 'r', toSide: 'l' },
      { from: 'pdp',    to: 'esc',    label: 'escalate', fromSide: 'r', toSide: 'l' },
      { from: 'allow',  to: 'reaff',  fromSide: 'r', toSide: 'l' },
      { from: 'deny',   to: 'reaff',  label: 'refused', fromSide: 'r', toSide: 'l', at: 0.25 },
      { from: 'esc',    to: 'ask',    dash: true, fromSide: 'b', toSide: 't' },
      { from: 'ask',    to: 'deny',   dash: true, label: 'denied · expired', fromSide: 'l', toSide: 'l', via: { x: 545, y: 620 } },
      { from: 'ask',    to: 'allow',  dash: true, label: 'approved', fromSide: 'r', toSide: 'b', via: { x: 816, y: 490 } },
      { from: 'reaff',  to: 'avail',  label: 'refusals' },
      { from: 'reaff',  to: 'skill',  label: 'real outcomes', fromSide: 'r', toSide: 'r', ext: 18, at: 0.7 },
      { from: 'avail',  to: 'synth',  label: 'damps', fromSide: 'r', toSide: 'l', at: 0.35 },
      { from: 'synth',  to: 'select', label: 'the field competes' },
      { from: 'select', to: 'revoke', label: 'honored next tick' },
    ],
  },

  // ═══ 24 · THE JOINT RFC (HELM × Will) ═════════════════════
  {
    file: 'policy-joint-rfc.svg',
    title: 'Denials that teach — the HELM × Will seam',
    subtitle: 'The joint RFC in one picture: a denial carries WHY it is final and WHAT would have worked; four receipt values become four distinct fates in the mind — and competence is never one of them',
    width: 1360, height: 880,
    legend: [ 'world', 'infra', 'agency' ],
    groups: [
      { x: 44,   y: 118, w: 236,  h: 460, label: 'producer — HELM',   cat: 'world' },
      { x: 300,  y: 118, w: 236,  h: 460, label: 'the wire',          cat: 'infra' },
      { x: 556,  y: 118, w: 250,  h: 460, label: 'the seam — will',   cat: 'infra' },
      { x: 826,  y: 118, w: 250,  h: 560, label: 'wire value → our fate',            cat: 'infra' },
      { x: 1096, y: 118, w: 224,  h: 560, label: 'what the mind learns',              cat: 'agency' },
      { x: 44,   y: 700, w: 1276, h: 120, label: 'the invariants — what a refusal can never do', cat: 'agency' },
    ],
    nodes: [
      // producer
      { id: 'rule',     x: 62,   y: 190, w: 200, label: 'The rule that fired',  sub: 'one frozen policy snapshot',        cat: 'world' },
      { id: 'receipt',  x: 62,   y: 340, w: 200, label: 'Signed receipt',       sub: 'the decision, with evidence',       cat: 'world' },
      { id: 'profile',  x: 62,   y: 490, w: 200, label: 'Opt-in per profile',   sub: 'absent when off — presence speaks', cat: 'world' },
      // the wire
      { id: 'finality', x: 318,  y: 190, w: 200, label: 'finality',             sub: 'WHY it is final — four values',     cat: 'infra' },
      { id: 'counter',  x: 318,  y: 340, w: 200, label: 'counterfactual',       sub: 'WHAT would have worked',            cat: 'infra' },
      { id: 'never',    x: 318,  y: 490, w: 200, label: 'never enumerations',   sub: 'an allowlist is an infra map',      cat: 'infra' },
      // the seam
      { id: 'adapter',  x: 576,  y: 190, w: 210, label: 'HELM adapter',         sub: 'the only place HELM names live',    cat: 'infra' },
      { id: 'pep',      x: 576,  y: 340, w: 210, label: 'effectorController — PEP', sub: 'the one tract every effect crosses', cat: 'infra' },
      { id: 'tape',     x: 576,  y: 490, w: 210, label: 'Verdict tape',         sub: 'recorded at the tick it arrived',   cat: 'infra' },
      // four fates
      { id: 'forbid',   x: 846,  y: 160, w: 210, label: 'class_forbidden',      sub: '→ class · let go of it',            cat: 'infra' },
      { id: 'ungrant',  x: 846,  y: 300, w: 210, label: 'ungranted',            sub: '→ escalate · held, not denied',     cat: 'infra' },
      { id: 'param',    x: 846,  y: 440, w: 210, label: 'instance_parameter',   sub: '→ parameter · not that, this much', cat: 'infra' },
      { id: 'context',  x: 846,  y: 580, w: 210, label: 'instance_context',     sub: '→ context · not about the act',     cat: 'infra' },
      // what the mind learns
      { id: 'avail',    x: 1112, y: 160, w: 192, label: 'Availability — may',   sub: 'cut hard · envelopes erased',       cat: 'agency' },
      { id: 'voice',    x: 1112, y: 300, w: 192, label: 'The ask — voiced once', sub: 'approve ⇒ the same intent resumes', cat: 'agency' },
      { id: 'envelope', x: 1112, y: 440, w: 192, label: 'Envelope — how much',  sub: 'clamps habit · informs thought',    cat: 'agency' },
      { id: 'nodelta',  x: 1112, y: 580, w: 192, label: 'No delta at all',      sub: 'record it · free it · touch nothing', cat: 'agency' },
      // the invariants
      { id: 'outcome',  x: 62,   y: 730, w: 200, label: 'Real outcomes',        sub: 'the world actually ran it',         cat: 'world' },
      { id: 'skill',    x: 330,  y: 730, w: 210, label: 'LearnedSkill — can',   sub: 'only these ever write here',        cat: 'agency', glow: true },
      { id: 'replay',   x: 596,  y: 730, w: 210, label: 'Byte-identical replay', sub: 'tape re-fed · PDP never re-asked', cat: 'infra' },
      { id: 'probe',    x: 846,  y: 730, w: 210, label: 'Re-probe survives',    sub: 'a relaxed policy is rediscovered',  cat: 'agency' },
      { id: 'quiet',    x: 1112, y: 730, w: 192, label: 'No policy ⇒ no trace', sub: 'identical to a pre-policy mind',    cat: 'infra' },
    ],
    edges: [
      { from: 'rule',     to: 'receipt' },
      { from: 'profile',  to: 'receipt',  dash: true, label: 'discloses', fromSide: 't', toSide: 'b' },
      { from: 'receipt',  to: 'finality', fromSide: 'r', toSide: 'l' },
      { from: 'receipt',  to: 'counter',  fromSide: 'r', toSide: 'l' },
      { from: 'never',    to: 'counter',  dash: true, label: 'constrains', fromSide: 't', toSide: 'b' },
      { from: 'finality', to: 'adapter' },
      { from: 'counter',  to: 'adapter',  dash: true, at: 0.35 },
      { from: 'adapter',  to: 'pep',      label: 'Verdict' },
      { from: 'pep',      to: 'tape',     dash: true, label: 'every verdict' },
      // The axis collapse: HELM sends four finality values; only `ungranted`
      // becomes a third DECISION here (held, not denied) — so it is the one
      // arm worth labelling. The group title carries the 3-deny/1-ask split.
      { from: 'pep',      to: 'forbid',   fromSide: 'r', toSide: 'l' },
      { from: 'pep',      to: 'ungrant',  fromSide: 'r', toSide: 'l' },
      { from: 'pep',      to: 'param',    fromSide: 'r', toSide: 'l' },
      { from: 'pep',      to: 'context',  fromSide: 'r', toSide: 'l' },
      { from: 'forbid',   to: 'avail',    fromSide: 'r', toSide: 'l' },
      { from: 'ungrant',  to: 'voice',    fromSide: 'r', toSide: 'l' },
      { from: 'param',    to: 'envelope', fromSide: 'r', toSide: 'l' },
      { from: 'context',  to: 'nodelta',  fromSide: 'r', toSide: 'l' },
      { from: 'outcome',  to: 'skill' },
      { from: 'tape',     to: 'replay',   label: 'recorded', fromSide: 'b', toSide: 't' },
    ],
  },
]

for( const g of graphs ){
  const svg = render( g )
  writeFileSync( join( OUT, g.file ), svg )
  console.log(`✓ ${ g.file }  (${ ( svg.length / 1024 ).toFixed( 1 ) } KB)`)
}
console.log(`\n${ graphs.length } graphs → docs/graphs/`)
