// ─────────────────────────────────────────────────────────────
// docs/graphs/generate.ts — the architecture knowledge graphs
// ─────────────────────────────────────────────────────────────
//
//   bun docs/graphs/generate.ts        → re-emits docs/graphs/*.svg
//
// Each graph is a declarative spec rendered through the shared design system
// (lib.ts) — one palette, one visual language across the whole set. These are
// the visual layer of the architecture documentation; the paired prose lives
// (or will live) alongside each graph — see .TODO/KNOWLEDGE_GRAPHS.md.
// ─────────────────────────────────────────────────────────────

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { render, type Graph } from './lib'

const OUT = dirname( fileURLToPath( import.meta.url ) )

const graphs: Graph[] = [

  // ═══ 1 · MEMORY ═══════════════════════════════════════════
  {
    file: 'memory-cycle.svg',
    title: 'Memory — how experience becomes a self',
    subtitle: 'Working memory → episodic consolidation → beliefs; maintenance loops below, recall back into thought on the right',
    width: 1360, height: 780,
    legend: [ 'perceptual', 'memory', 'meta', 'executive', 'llm', 'infra' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 232, label: 'intake',                     cat: 'perceptual' },
      { x: 300,  y: 118, w: 216, h: 232, label: 'short-term',                 cat: 'memory' },
      { x: 556,  y: 118, w: 500, h: 292, label: 'consolidation · long-term',  cat: 'memory' },
      { x: 556,  y: 438, w: 500, h: 232, label: 'maintenance · offline',      cat: 'memory' },
      { x: 1076, y: 118, w: 240, h: 292, label: 'recall into thought',        cat: 'executive' },
    ],
    nodes: [
      { id: 'percepts',  x: 62,   y: 150, label: 'Percepts',               sub: 'senses.*.percept',            cat: 'perceptual' },
      { id: 'exchange',  x: 62,   y: 262, label: 'Conversation turns',     sub: 'audition exchanges',          cat: 'perceptual' },
      { id: 'wm',        x: 318,  y: 205, w: 180, label: 'WorkingMemory',  sub: 'activation · decay',          cat: 'memory' },
      { id: 'consol',    x: 576,  y: 150, w: 196, label: 'EpisodicConsolidator', sub: 'episodes · dedup',      cat: 'memory' },
      { id: 'embed',     x: 576,  y: 280, w: 196, label: 'Embedder',       sub: 'vector encode (live only)',   cat: 'llm', glow: true },
      { id: 'vector',    x: 838,  y: 280, w: 190, label: 'Vector memory',  sub: 'semantic index',              cat: 'memory' },
      { id: 'semantic',  x: 838,  y: 150, w: 190, label: 'SemanticIntegrator', sub: 'beliefs · confidence',    cat: 'memory' },
      { id: 'forget',    x: 576,  y: 470, w: 196, label: 'ForgettingCurve', sub: 'decay · prune',              cat: 'memory' },
      { id: 'dream',     x: 576,  y: 580, w: 196, label: 'DreamSimulator', sub: 'offline replay',              cat: 'memory' },
      { id: 'spaced',    x: 838,  y: 470, w: 190, label: 'SpacedRepetition', sub: 'reinforce on schedule',     cat: 'memory' },
      { id: 'narrator',  x: 838,  y: 580, w: 190, label: 'Autobiographical', sub: 'narrator — the life story', cat: 'meta' },
      { id: 'recall',    x: 1094, y: 150, w: 204, label: 'buildExecutiveContext', sub: '## Relevant Memories', cat: 'executive' },
      { id: 'prompt',    x: 1094, y: 280, w: 204, label: 'Executive & facet prompts', sub: 'master · conversation', cat: 'llm', glow: true },
      { id: 'pma',       x: 1094, y: 560, w: 204, label: 'PMA distill',    sub: 'beliefs · digests · narrative', cat: 'infra' },
    ],
    edges: [
      { from: 'percepts', to: 'wm' },
      { from: 'exchange', to: 'wm',      label: 'WM items' },
      { from: 'wm',       to: 'consol',  label: 'salient items' },
      { from: 'consol',   to: 'embed',   dash: true, label: 'embed', cat: 'llm' },
      { from: 'embed',    to: 'vector',  cat: 'llm' },
      { from: 'consol',   to: 'semantic' },
      { from: 'forget',   to: 'consol',  dash: true, label: 'prune',  fromSide: 'l', toSide: 'l', ext: 30 },
      { from: 'dream',    to: 'consol',  dash: true, label: 'replay', fromSide: 'l', toSide: 'l', ext: 56, at: 0.55 },
      { from: 'spaced',   to: 'semantic', dash: true, label: 'reinforce', fromSide: 'l', toSide: 'l', ext: 26 },
      { from: 'vector',   to: 'recall',  dash: true, label: 'semanticQuery' },
      { from: 'semantic', to: 'recall' },
      { from: 'recall',   to: 'prompt' },
      { from: 'semantic', to: 'pma',     dash: true, fromSide: 'r', toSide: 't', reach: 30 },
      { from: 'narrator', to: 'pma' },
    ],
  },

  // ═══ 2 · EXECUTIVE & FACETS ═══════════════════════════════
  {
    file: 'executive-dual-process.svg',
    title: 'Executive — dual-process thought & facets',
    subtitle: 'One consciousness: master cycle and every focused facet share identity, context and schema — reasoning launches and lands only at tick boundaries',
    width: 1360, height: 780,
    legend: [ 'perceptual', 'executive', 'llm', 'infra' ],
    groups: [
      { x: 284,  y: 118, w: 500, h: 330, label: 'the master cycle',                     cat: 'executive' },
      { x: 824,  y: 118, w: 492, h: 230, label: 'facet machinery — unified inference',  cat: 'executive' },
      { x: 824,  y: 378, w: 492, h: 230, label: 'tick-quantized seams (determinism)',   cat: 'infra' },
    ],
    nodes: [
      { id: 'salience', x: 60,   y: 150, label: 'Salience charge',  sub: 'events accrue pressure',        cat: 'perceptual' },
      { id: 'activate', x: 60,   y: 262, label: 'Activation gate',  sub: 'salience_charged → cycle',      cat: 'executive' },
      { id: 'context',  x: 300,  y: 150, w: 208, label: 'buildExecutiveContext', sub: 'state · goals · memories · abilities', cat: 'executive' },
      { id: 'gate',     x: 300,  y: 262, w: 208, label: 'Effort gate', sub: 'selectProcess: fast | deliberate', cat: 'executive' },
      { id: 'ideate',   x: 560,  y: 150, w: 200, label: 'Ideation (propose)', sub: 'divergent candidates', cat: 'llm', glow: true },
      { id: 'decide',   x: 560,  y: 300, w: 200, label: 'Decision call', sub: 'PromptFactory · LLMDirector', cat: 'llm', glow: true },
      { id: 'commands', x: 560,  y: 470, w: 210, label: 'buildStateCommands', sub: 'goals · beliefs · narrative · ideomotor', cat: 'executive' },
      { id: 'commit',   x: 560,  y: 620, w: 210, label: 'State commit', sub: 'command buffer (serial)',    cat: 'infra' },
      { id: 'recorder', x: 300,  y: 620, w: 208, label: 'Completion recorder', sub: 'record ↔ re-feed (replay)', cat: 'infra' },
      { id: 'creators', x: 60,   y: 470, w: 208, label: 'Creator engines', sub: 'audition · deliberation · planning', cat: 'infra' },
      { id: 'superv',   x: 850,  y: 150, w: 200, label: 'FacetSupervisor', sub: 'budget · reap idle, never busy', cat: 'executive' },
      { id: 'facet',    x: 850,  y: 262, w: 200, label: 'Facet',      sub: 'a focused instance of the SAME self', cat: 'executive' },
      { id: 'report',   x: 1110, y: 150, w: 190, label: 'report()',   sub: 'queued — never launches raw',  cat: 'executive' },
      { id: 'pump',     x: 1110, y: 262, w: 190, label: 'Per-tick pump', sub: 'frozen-snapshot launch',    cat: 'executive' },
      { id: 'inbox',    x: 1110, y: 410, w: 190, label: 'CompletionInbox', sub: 'decisions land at Phase 2', cat: 'executive' },
      { id: 'subs',     x: 1110, y: 528, w: 190, label: 'Subscribers', sub: 'audition reply · deliberation', cat: 'infra' },
      { id: 'sync',     x: 850,  y: 410, w: 200, label: 'Master sync', sub: 'reasoning broadcast to facets', cat: 'executive' },
    ],
    edges: [
      { from: 'salience', to: 'activate' },
      { from: 'activate', to: 'context', toSide: 'l' },
      { from: 'context',  to: 'gate' },
      { from: 'gate',     to: 'ideate',  label: 'deliberate', cat: 'llm', at: 0.3 },
      { from: 'gate',     to: 'decide',  label: 'fast', cat: 'llm' },
      { from: 'ideate',   to: 'decide',  label: 'candidates', cat: 'llm' },
      { from: 'decide',   to: 'commands' },
      { from: 'commands', to: 'commit' },
      { from: 'decide',   to: 'recorder', dash: true, label: 'record', fromSide: 'l', toSide: 't' },
      { from: 'creators', to: 'superv',  label: 'spawnFacet()', fromSide: 'b', toSide: 'b', reach: 90, at: 0.3 },
      { from: 'creators', to: 'report',  dash: true, label: 'setFocus · report', fromSide: 't', toSide: 't', reach: 46, at: 0.22 },
      { from: 'superv',   to: 'facet' },
      { from: 'report',   to: 'pump',    label: 'queued' },
      { from: 'facet',    to: 'pump',    dash: true, label: 'launch' },
      { from: 'pump',     to: 'decide',  dash: true, label: 'same prompt path', cat: 'llm', fromSide: 'b', toSide: 'r', reach: 26, at: 0.6 },
      { from: 'decide',   to: 'inbox',   dash: true, label: 'resolution enqueued', cat: 'llm', fromSide: 'b', toSide: 'l', reach: 40, at: 0.45 },
      { from: 'inbox',    to: 'subs',    label: 'Phase-2 drain' },
      { from: 'commands', to: 'sync',    dash: true },
      { from: 'sync',     to: 'facet',   dash: true },
    ],
  },

  // ═══ 3 · AGENCY ═══════════════════════════════════════════
  {
    file: 'agency-pipeline.svg',
    title: 'Agency — how a Will acts, and learns to act',
    subtitle: 'Actions are found in the situation, not picked from a catalog: affordances compete, intention biases, enaction returns as learning',
    width: 1360, height: 780,
    legend: [ 'world', 'perceptual', 'executive', 'agency', 'llm' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 560, label: 'sources of the field', cat: 'agency' },
      { x: 300,  y: 118, w: 236, h: 400, label: 'perceive · afford',    cat: 'agency' },
      { x: 560,  y: 118, w: 246, h: 330, label: 'compete',              cat: 'agency' },
      { x: 826,  y: 118, w: 250, h: 440, label: 'enact',                cat: 'agency' },
      { x: 1096, y: 118, w: 224, h: 440, label: 'learn',                cat: 'agency' },
    ],
    nodes: [
      { id: 'innate',   x: 62,   y: 150, label: 'Innate schemas',   sub: 'orient · rest · reach-out…',    cat: 'agency' },
      { id: 'external', x: 62,   y: 262, label: 'Host abilities',   sub: 'meaning + priors (+ MCP tools)', cat: 'world' },
      { id: 'perceptS', x: 62,   y: 374, label: 'Percepts · entities', sub: 'salient things & people',    cat: 'perceptual' },
      { id: 'ideo',     x: 62,   y: 486, label: 'Ideomotor intents', sub: 'imagined acts + conscious args', cat: 'executive' },
      { id: 'planp',    x: 62,   y: 598, label: 'Plan priors',      sub: 'frontier-step bias',            cat: 'executive' },
      { id: 'repert',   x: 318,  y: 205, w: 200, label: 'SchemaRepertoire', sub: 'innate + external + learned', cat: 'agency' },
      { id: 'synth',    x: 318,  y: 400, w: 200, label: 'AffordanceSynthesizer', sub: 'the field — attention-capped', cat: 'agency' },
      { id: 'delib',    x: 578,  y: 180, w: 210, label: 'DeliberationEngine', sub: 'System 2 via a unified facet', cat: 'llm', glow: true },
      { id: 'selector', x: 578,  y: 360, w: 210, label: 'ActionSelector', sub: 'goal + reward + drive − cost − risk', cat: 'agency' },
      { id: 'comm',     x: 846,  y: 180, w: 210, label: 'ProactiveCommunicator', sub: 'communicate → outbox',  cat: 'social' },
      { id: 'motor',    x: 846,  y: 360, w: 210, label: 'MotorSchemaExecutor', sub: 'stance · communicate · external', cat: 'agency' },
      { id: 'invoke',   x: 846,  y: 490, w: 210, label: 'Effector invocation', sub: 'the HOST runs the action',  cat: 'world' },
      { id: 'ack',      x: 1112, y: 490, w: 192, label: 'Execution ack', sub: 'outcome + metrics',          cat: 'world' },
      { id: 'reaff',    x: 1112, y: 360, w: 192, label: 'ReafferenceEngine', sub: 'surprise = predicted − actual', cat: 'agency' },
      { id: 'skills',   x: 1112, y: 205, w: 192, label: 'LearnedSkill', sub: 'value · habit · param priors', cat: 'agency' },
    ],
    edges: [
      { from: 'innate',   to: 'repert' },
      { from: 'external', to: 'repert' },
      { from: 'repert',   to: 'synth',   label: 'enactable schemas' },
      { from: 'perceptS', to: 'synth',   label: 'bind targets' },
      { from: 'ideo',     to: 'synth',   label: 'pre-activate (+args)' },
      { from: 'planp',    to: 'synth',   label: 'bias', toSide: 'b', reach: 10 },
      { from: 'synth',    to: 'selector', label: 'affordances' },
      { from: 'selector', to: 'delib',   label: 'contested · high-stakes', cat: 'llm' },
      { from: 'delib',    to: 'motor',   label: 'chosen intent', cat: 'llm' },
      { from: 'selector', to: 'motor',   label: 'System 1 — habitual', fromSide: 'b', toSide: 'b', ext: 40 },
      { from: 'motor',    to: 'comm',    label: 'communicate' },
      { from: 'motor',    to: 'invoke',  label: 'external' },
      { from: 'invoke',   to: 'ack' },
      { from: 'ack',      to: 'reaff',   label: 'reafference' },
      { from: 'motor',    to: 'reaff',   dash: true, label: 'prediction', fromSide: 't', toSide: 't', ext: 30 },
      { from: 'reaff',    to: 'skills' },
      { from: 'skills',   to: 'repert',  dash: true, label: 'proceduralize → composites', fromSide: 't', toSide: 't', ext: 40, at: 0.45 },
    ],
  },

  // ═══ 4 · AUDITION ═════════════════════════════════════════
  {
    file: 'audition-conversation.svg',
    title: 'Audition — how a conversation flows through the mind',
    subtitle: 'Deliver → perceive → one focused facet reasons → the reply lands tick-quantized in the outbox — and the exchange becomes memory',
    width: 1360, height: 780,
    legend: [ 'world', 'perceptual', 'executive', 'llm', 'memory' ],
    groups: [
      { x: 44,   y: 118, w: 236, h: 430, label: 'host boundary',          cat: 'world' },
      { x: 300,  y: 118, w: 236, h: 430, label: 'perception · salience',  cat: 'perceptual' },
      { x: 556,  y: 118, w: 250, h: 430, label: 'the facet turn',         cat: 'executive' },
      { x: 826,  y: 118, w: 494, h: 320, label: 'the reply path',         cat: 'llm' },
      { x: 826,  y: 468, w: 494, h: 180, label: 'into memory',            cat: 'memory' },
    ],
    nodes: [
      { id: 'host',     x: 62,   y: 150, label: 'Host / interlocutor', sub: 'say · perceive · MCP · HTTP',  cat: 'world' },
      { id: 'stem',     x: 62,   y: 290, label: 'WillStem.ingestText', sub: 'sensory controller',           cat: 'infra' },
      { id: 'grants',   x: 62,   y: 430, label: 'AccessGrants',      sub: "'listen' granted?",              cat: 'agency' },
      { id: 'percept',  x: 318,  y: 290, w: 200, label: 'Language percept', sub: 'salience-weighted',       cat: 'perceptual' },
      { id: 'digest',   x: 318,  y: 430, w: 200, label: 'Thread digest', sub: 'rolling conversation state', cat: 'memory' },
      { id: 'turnq',    x: 318,  y: 150, w: 200, label: 'Turn queue',  sub: 'one turn per entity',          cat: 'infra' },
      { id: 'attach',   x: 62,   y: 600, label: 'Attachment · goals', sub: 'closeness + topic overlap',     cat: 'affective' },
      { id: 'focus',    x: 576,  y: 150, w: 210, label: 'Focus + recall query', sub: 'the live message drives recall', cat: 'executive' },
      { id: 'facet',    x: 576,  y: 290, w: 210, label: 'Conversation facet', sub: 'spawned from the executive', cat: 'executive' },
      { id: 'quant',    x: 576,  y: 430, w: 210, label: 'report → pump → inbox', sub: 'tick-quantized launch & landing', cat: 'executive' },
      { id: 'reason',   x: 846,  y: 220, w: 200, label: 'Reply reasoning', sub: '[REPLY_TEXT] dialect',     cat: 'llm', glow: true },
      { id: 'stream',   x: 1116, y: 150, w: 188, label: 'Chunk stream', sub: 'only reply text escapes',     cat: 'world' },
      { id: 'writer',   x: 846,  y: 360, w: 200, label: 'OutboxWriter', sub: 'bubbles · threadId',          cat: 'infra' },
      { id: 'outbox',   x: 1116, y: 360, w: 188, label: 'Outbox → host', sub: 'delivery + ack loop',        cat: 'world' },
      { id: 'exchange', x: 846,  y: 528, w: 200, label: 'Exchange memory', sub: 'WM item → episodic → vector', cat: 'memory' },
      { id: 'recallq',  x: 1116, y: 528, w: 188, label: 'Next-turn recall', sub: 'the past shapes the reply', cat: 'memory' },
    ],
    edges: [
      { from: 'host',    to: 'stem' },
      { from: 'stem',    to: 'grants',  label: 'gate' },
      { from: 'grants',  to: 'percept', label: 'allowed', fromSide: 'r', toSide: 'l' },
      { from: 'stem',    to: 'turnq',   dash: true, label: 'arm turn', fromSide: 'r', toSide: 'l', reach: 10 },
      { from: 'percept', to: 'digest',  label: 'append user turn' },
      { from: 'attach',  to: 'percept', dash: true, label: 'salience inputs', fromSide: 'r', toSide: 'b', reach: 24 },
      { from: 'percept', to: 'facet' },
      { from: 'turnq',   to: 'facet',   dash: true, fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'digest',  to: 'focus',   dash: true, label: 'context', fromSide: 't', toSide: 'l', reach: 20, at: 0.35 },
      { from: 'focus',   to: 'facet' },
      { from: 'facet',   to: 'quant',   label: 'report' },
      { from: 'quant',   to: 'reason',  label: 'launch @ tick', cat: 'llm' },
      { from: 'reason',  to: 'stream',  dash: true, label: 'tokens', cat: 'llm' },
      { from: 'reason',  to: 'writer',  label: 'decision lands (Phase 2)', at: 0.55 },
      { from: 'writer',  to: 'outbox' },
      { from: 'writer',  to: 'exchange', dash: true, label: 'exchange' },
      { from: 'exchange', to: 'recallq', dash: true },
    ],
  },

  // ═══ 5 · BODY & FEELING ═══════════════════════════════════
  {
    file: 'affect-body.svg',
    title: 'Body & feeling — regulation and affect',
    subtitle: 'Seven evaluators blend into a real affective state; the body’s budgets gate thought, attention and action — mood is state, not a prompt string',
    width: 1360, height: 830,
    legend: [ 'regulatory', 'affective', 'executive', 'llm', 'world' ],
    groups: [
      { x: 296,  y: 108, w: 226, h: 500, label: 'regulatory — the body', cat: 'regulatory' },
      { x: 556,  y: 108, w: 226, h: 660, label: 'affective evaluators',  cat: 'affective' },
      { x: 1096, y: 108, w: 226, h: 560, label: 'what feeling touches',  cat: 'executive' },
    ],
    nodes: [
      { id: 'events',  x: 60,   y: 200, label: 'Percepts & outcomes', sub: 'what just happened',        cat: 'perceptual' },
      { id: 'body',    x: 60,   y: 360, label: 'Body metrics',   sub: 'energy · sleep · stress',        cat: 'infra' },
      { id: 'energy',  x: 310,  y: 140, w: 196, label: 'EnergyRegulator',  sub: 'actions cost · rest restores', cat: 'regulatory' },
      { id: 'sleep',   x: 310,  y: 232, w: 196, label: 'SleepPressure',    sub: 'cognitive capacity',   cat: 'regulatory' },
      { id: 'circ',    x: 310,  y: 324, w: 196, label: 'CircadianOscillator', sub: 'phase · time of day', cat: 'regulatory' },
      { id: 'stress',  x: 310,  y: 416, w: 196, label: 'StressRegulator',  sub: 'load · decay',         cat: 'regulatory' },
      { id: 'attn',    x: 310,  y: 508, w: 196, label: 'AttentionAllocator', sub: 'capacity budget',    cat: 'regulatory' },
      { id: 'threat',  x: 570,  y: 140, w: 196, label: 'Threat',      sub: 'danger appraisal',      cat: 'affective' },
      { id: 'reward',  x: 570,  y: 230, w: 196, label: 'Reward',      sub: 'gain appraisal',        cat: 'affective' },
      { id: 'loss',    x: 570,  y: 320, w: 196, label: 'Loss',        sub: 'what was taken',        cat: 'affective' },
      { id: 'frust',   x: 570,  y: 410, w: 196, label: 'Frustration', sub: 'blocked intentions',    cat: 'affective' },
      { id: 'attach2', x: 570,  y: 500, w: 196, label: 'Attachment',  sub: 'bonds · belonging',     cat: 'affective' },
      { id: 'aesth',   x: 570,  y: 590, w: 196, label: 'Aesthetic',   sub: 'curiosity · boredom',   cat: 'affective' },
      { id: 'moral',   x: 570,  y: 680, w: 196, label: 'Moral',       sub: 'values violated?',      cat: 'affective' },
      { id: 'blend',   x: 836,  y: 400, w: 210, label: 'AffectiveBlender', sub: 'valence · arousal · dominance · blends', cat: 'affective', glow: true },
      { id: 'effort',  x: 836,  y: 150, w: 210, label: 'Effort gate & caps', sub: 'quality modulation · field width', cat: 'executive' },
      { id: 'prompt2', x: 1110, y: 150, w: 196, label: 'Executive prompt', sub: 'mood colors thought',  cat: 'llm', glow: true },
      { id: 'select2', x: 1110, y: 290, w: 196, label: 'Action selection', sub: 'valence priors · risk', cat: 'agency' },
      { id: 'salW',    x: 1110, y: 430, w: 196, label: 'Percept salience', sub: 'attention weighting',  cat: 'perceptual' },
      { id: 'emit',    x: 1110, y: 570, w: 196, label: "on('emotion')",   sub: 'hosts observe affect',  cat: 'world' },
    ],
    edges: [
      { from: 'events', to: 'threat',  label: 'feeds all seven', at: 0.45 },
      { from: 'body',   to: 'energy',  fromSide: 't', toSide: 'l', reach: 12 },
      { from: 'body',   to: 'stress',  label: 'load' },
      { from: 'circ',   to: 'sleep',   dash: true },
      { from: 'threat', to: 'blend' },
      { from: 'reward', to: 'blend' },
      { from: 'loss',   to: 'blend' },
      { from: 'frust',  to: 'blend' },
      { from: 'attach2', to: 'blend' },
      { from: 'aesth',  to: 'blend' },
      { from: 'moral',  to: 'blend' },
      { from: 'energy', to: 'effort', fromSide: 't', toSide: 't', ext: 36, label: 'budgets', at: 0.72 },
      { from: 'attn',   to: 'select2', dash: true, label: 'attention cap', fromSide: 'b', toSide: 'b', ext: 200, at: 0.55 },
      { from: 'stress', to: 'blend',  dash: true, label: 'arousal', fromSide: 'r', toSide: 'l', at: 0.82 },
      { from: 'effort', to: 'prompt2' },
      { from: 'blend',  to: 'prompt2', fromSide: 'r', toSide: 'b', reach: 8 },
      { from: 'blend',  to: 'select2' },
      { from: 'blend',  to: 'salW' },
      { from: 'blend',  to: 'emit',   fromSide: 'b', toSide: 'l', reach: 16 },
    ],
  },

  // ═══ 6 · THE TICK ═════════════════════════════════════════
  {
    file: 'determinism-tick.svg',
    title: 'The tick — command-buffer determinism & replay',
    subtitle: 'Serial engines write commands, never state; async LLM chains launch and land only at tick boundaries; a transcript makes any life re-runnable byte-for-byte',
    width: 1360, height: 700,
    legend: [ 'infra', 'executive', 'llm', 'world' ],
    groups: [
      { x: 284,  y: 118, w: 520, h: 440, label: 'one tick — serial & pure',          cat: 'infra' },
      { x: 834,  y: 248, w: 226, h: 310, label: 'async chains, quantized',           cat: 'executive' },
      { x: 1090, y: 118, w: 226, h: 440, label: 'the replay seam',                   cat: 'world' },
    ],
    nodes: [
      { id: 'clock',   x: 60,   y: 150, w: 204, label: 'Clock',        sub: 'wall interval | fixed Δ (replay)', cat: 'infra' },
      { id: 'prng',    x: 60,   y: 290, w: 204, label: 'Seeded PRNG',  sub: 'context.random(), never Math.random', cat: 'infra' },
      { id: 'orch',    x: 300,  y: 150, w: 214, label: 'CognitiveOrchestrator', sub: 'engines in priority order', cat: 'infra', glow: true },
      { id: 'engines', x: 300,  y: 290, w: 214, label: 'Engines react()', sub: 'frozen state → commands',  cat: 'executive' },
      { id: 'buffer',  x: 300,  y: 430, w: 214, label: 'Command buffer', sub: 'no in-place writes',        cat: 'infra' },
      { id: 'valid',   x: 574,  y: 430, w: 200, label: 'Validators',  sub: 'abort ⇒ whole tick discarded', cat: 'infra' },
      { id: 'commit2', x: 574,  y: 290, w: 200, label: 'Commit',      sub: 'snapshot (COW) · metrics',     cat: 'infra' },
      { id: 'phase2',  x: 574,  y: 150, w: 200, label: 'Phase 2 — inbox drain', sub: 'facet effects land here', cat: 'executive' },
      { id: 'pump3',   x: 850,  y: 320, w: 190, label: 'Pump · CompletionInbox', sub: 'launch @ tick · land @ Phase 2', cat: 'executive' },
      { id: 'llm3',    x: 850,  y: 470, w: 190, label: 'LLM calls',   sub: 'async — resolve off-tick',     cat: 'llm', glow: true },
      { id: 'rec3',    x: 1106, y: 470, w: 194, label: 'Completion recorder', sub: 'transcript of every call', cat: 'infra' },
      { id: 'refeed',  x: 1106, y: 320, w: 194, label: 'Re-feed source', sub: 'prompt-keyed · strict',     cat: 'infra' },
      { id: 'replay',  x: 1106, y: 150, w: 194, label: 'Byte-identical replay', sub: 'same seed + inputs ⇒ same mind', cat: 'world', glow: true },
    ],
    edges: [
      { from: 'clock',   to: 'orch' },
      { from: 'prng',    to: 'engines', dash: true },
      { from: 'orch',    to: 'engines', label: 'tick N' },
      { from: 'engines', to: 'buffer' },
      { from: 'buffer',  to: 'valid' },
      { from: 'valid',   to: 'commit2', label: 'ok' },
      { from: 'commit2', to: 'phase2' },
      { from: 'phase2',  to: 'orch',   dash: true, label: 'tick N+1', fromSide: 't', toSide: 't', ext: 34 },
      { from: 'engines', to: 'pump3',  dash: true, label: 'react() pumps', fromSide: 'b', toSide: 'l', reach: 36, at: 0.62 },
      { from: 'pump3',   to: 'llm3',   cat: 'llm', label: 'launch' },
      { from: 'llm3',    to: 'pump3',  dash: true, cat: 'llm', label: 'enqueue', fromSide: 'r', toSide: 'r', ext: 24 },
      { from: 'pump3',   to: 'phase2', dash: true, cat: 'llm', label: 'drained @ Phase 2', fromSide: 't', toSide: 'r', ext: 55 },
      { from: 'llm3',    to: 'rec3',   dash: true, label: 'record' },
      { from: 'rec3',    to: 'refeed', label: 'transcript' },
      { from: 'refeed',  to: 'llm3',   dash: true, label: 'replay serves', fromSide: 'l', toSide: 't', reach: 8, at: 0.5 },
      { from: 'refeed',  to: 'replay' },
    ],
  },

  // ═══ 7 · PMA ══════════════════════════════════════════════
  {
    file: 'pma-lifecycle.svg',
    title: 'PMA — the Persistent Mind Artifact',
    subtitle: 'Distill a living mind into a portable artifact; wake the same self anywhere — identity, memory, relationships and skill survive the boundary',
    width: 1360, height: 660,
    legend: [ 'world', 'infra', 'executive', 'memory', 'social', 'agency' ],
    groups: [
      { x: 44,  y: 118, w: 760, h: 470, label: 'the lifecycle',        cat: 'infra' },
      { x: 826, y: 118, w: 494, h: 470, label: 'what travels — the self', cat: 'memory' },
    ],
    nodes: [
      { id: 'hosts',   x: 62,   y: 150, w: 190, label: 'Hosts',       sub: 'SDK · MCP · sidecar · backend', cat: 'world' },
      { id: 'living',  x: 62,   y: 330, w: 190, label: 'A living Will', sub: 'ticking · accreting',        cat: 'executive', glow: true },
      { id: 'distill', x: 330,  y: 210, w: 190, label: 'Distill',     sub: 'save() — non-destructive · hibernate()', cat: 'infra' },
      { id: 'artifact', x: 590, y: 330, w: 190, label: 'PMA artifact', sub: 'a portable JSON self',        cat: 'memory', glow: true },
      { id: 'wake',    x: 330,  y: 460, w: 190, label: 'Wake',        sub: 'paused assembly → load → resume', cat: 'infra' },
      { id: 'eval',    x: 590,  y: 480, w: 190, label: 'Reconstruction eval', sub: 'fidelity report — verified restore', cat: 'infra' },
      { id: 'ident',   x: 856,  y: 150, w: 200, label: 'Identity & traits', sub: 'developed, not configured', cat: 'meta' },
      { id: 'belief2', x: 856,  y: 260, w: 200, label: 'Beliefs & memories', sub: 'semantic + episodic digests', cat: 'memory' },
      { id: 'bonds',   x: 856,  y: 370, w: 200, label: 'Relationships', sub: 'bonds · reputations · dossiers', cat: 'social' },
      { id: 'skills3', x: 856,  y: 480, w: 200, label: 'Skills & composites', sub: 'learned competence',   cat: 'agency' },
      { id: 'narr2',   x: 1106, y: 315, w: 194, label: 'Narrative & persona prior', sub: 'the story of me', cat: 'meta' },
    ],
    edges: [
      { from: 'hosts',   to: 'distill', dash: true, label: 'shutdown', fromSide: 'r', toSide: 't', reach: 10 },
      { from: 'hosts',   to: 'living',  dash: true, label: 'boot' },
      { from: 'living',  to: 'distill', fromSide: 't', toSide: 'l', reach: 16 },
      { from: 'distill', to: 'artifact', fromSide: 'r', toSide: 't', reach: 16 },
      { from: 'artifact', to: 'wake',   fromSide: 'b', toSide: 'r', reach: 16 },
      { from: 'wake',    to: 'living',  label: 'the SAME self', fromSide: 'l', toSide: 'b', reach: 16 },
      { from: 'artifact', to: 'eval',   dash: true, label: 'runPMAEval', fromSide: 'b', toSide: 't', reach: 4 },
      { from: 'artifact', to: 'ident',  fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'artifact', to: 'belief2', fromSide: 'r', toSide: 'l' },
      { from: 'artifact', to: 'bonds',  fromSide: 'r', toSide: 'l' },
      { from: 'artifact', to: 'skills3', fromSide: 'r', toSide: 'l', reach: 8 },
      { from: 'belief2', to: 'narr2',   dash: true, fromSide: 'r', toSide: 't', reach: 8 },
      { from: 'bonds',   to: 'narr2',   dash: true, fromSide: 'r', toSide: 'b', reach: 8 },
    ],
  },

  // ═══ 8 · THE COMPOSITION (capstone) ═══════════════════════
  {
    file: 'composition.svg',
    title: 'Will — the whole composition',
    subtitle: 'From any host surface, through the stem, onto one deterministic tick — where forty engines make a mind. The LLM is a component, recruited — never the substrate',
    width: 1360, height: 960,
    legend: [ 'world', 'infra', 'llm', 'memory', 'executive', 'agency' ],
    groups: [
      { x: 44,  y: 108, w: 1272, h: 130, label: 'hosts & world',                        cat: 'world' },
      { x: 44,  y: 258, w: 1272, h: 120, label: 'surfaces — one paradigm, four doors',  cat: 'infra' },
      { x: 44,  y: 398, w: 1272, h: 120, label: 'stem · tick · seams',                  cat: 'infra' },
      { x: 44,  y: 538, w: 1272, h: 330, label: 'the mind — 40+ engines on one tick',   cat: 'executive' },
    ],
    nodes: [
      { id: 'claude',  x: 66,   y: 146, w: 196, label: 'Claude Desktop / Code', sub: 'an MCP client',      cat: 'world' },
      { id: 'app',     x: 300,  y: 146, w: 170, label: 'Your app',      sub: 'Node / TypeScript',          cat: 'world' },
      { id: 'anylang', x: 508,  y: 146, w: 190, label: 'Any language',  sub: 'Python · Go · game server',  cat: 'world' },
      { id: 'studio',  x: 736,  y: 146, w: 210, label: 'Mindot backend / Studio', sub: 'hosted minds',     cat: 'world' },
      { id: 'mcptool', x: 984,  y: 146, w: 200, label: 'External MCP tools', sub: 'employed as abilities', cat: 'world' },
      { id: 'mcp',     x: 66,   y: 296, w: 196, label: 'will mcp',      sub: 'perceive · next_utterance',  cat: 'infra' },
      { id: 'facade',  x: 300,  y: 296, w: 170, label: 'Will facade',   sub: 'projections · PMA',          cat: 'infra' },
      { id: 'serve',   x: 508,  y: 296, w: 190, label: 'will serve',    sub: 'HTTP + SSE · Docker',        cat: 'infra' },
      { id: 'transp',  x: 736,  y: 296, w: 210, label: 'Transports',    sub: 'loopback · socket.io · stream', cat: 'infra' },
      { id: 'bridge',  x: 984,  y: 296, w: 200, label: 'connectMcpEffectors', sub: '@mindot/will/mcp',     cat: 'agency' },
      { id: 'stem2',   x: 66,   y: 436, w: 300, label: 'WillStem — the body', sub: 'ingest · outbox · effectors · PMA · replay tracts', cat: 'infra', glow: true },
      { id: 'orch2',   x: 430,  y: 436, w: 240, label: 'Tick orchestrator', sub: 'serial · command buffer · seeded', cat: 'infra' },
      { id: 'llm4',    x: 736,  y: 436, w: 210, label: 'LLMDirector',   sub: 'gate · recorder · mock | live', cat: 'llm', glow: true },
      { id: 'pma2',    x: 1010, y: 436, w: 174, label: 'PMA',           sub: 'distill ⇄ wake',             cat: 'memory', glow: true },
      { id: 'reg',     x: 80,   y: 586, w: 280, label: 'Regulatory ×5', sub: 'energy · sleep · circadian · stress · attention', cat: 'regulatory' },
      { id: 'perc',    x: 400,  y: 586, w: 300, label: 'Perceptual ×4 + Senses ×5', sub: 'extero · intero · social · novelty · audition…', cat: 'perceptual' },
      { id: 'aff',     x: 740,  y: 586, w: 260, label: 'Affective ×8',  sub: 'seven evaluators + blender', cat: 'affective' },
      { id: 'mem',     x: 1040, y: 586, w: 250, label: 'Memory ×6',     sub: 'WM · episodic · semantic · dream…', cat: 'memory' },
      { id: 'exec',    x: 80,   y: 736, w: 300, label: 'Executive & planning ×5', sub: 'dual-process · facets · plans · inhibition', cat: 'executive' },
      { id: 'agen',    x: 420,  y: 736, w: 280, label: 'Agency ×6',     sub: 'afford · select · deliberate · enact · learn', cat: 'agency' },
      { id: 'metac',   x: 740,  y: 736, w: 280, label: 'Meta-cognitive ×6', sub: 'introspection → persona prior', cat: 'meta' },
      { id: 'soc',     x: 1060, y: 736, w: 230, label: 'Social ×4',     sub: 'ToM · empathy · reputation · dossiers', cat: 'social' },
    ],
    edges: [
      { from: 'claude',  to: 'mcp' },
      { from: 'app',     to: 'facade' },
      { from: 'anylang', to: 'serve' },
      { from: 'studio',  to: 'transp' },
      { from: 'mcptool', to: 'bridge' },
      { from: 'mcp',     to: 'stem2' },
      { from: 'facade',  to: 'stem2' },
      { from: 'serve',   to: 'stem2', fromSide: 'b', toSide: 't', reach: 10 },
      { from: 'transp',  to: 'stem2', fromSide: 'b', toSide: 't', reach: 10 },
      { from: 'bridge',  to: 'agen',  dash: true, label: 'tools become abilities', fromSide: 'r', toSide: 't', via: { x: 1020, y: 690 } },
      { from: 'stem2',   to: 'orch2', label: 'tick' },
      { from: 'orch2',   to: 'perc',  label: 'every tick', fromSide: 'b', toSide: 't' },
      { from: 'llm4',    to: 'exec',  dash: true, cat: 'llm', fromSide: 'b', toSide: 'l', via: { x: 70, y: 528 } },
      { from: 'pma2',    to: 'stem2', dash: true, cat: 'memory', fromSide: 't', toSide: 't', ext: 26, at: 0.5, label: 'hibernate ⇄ wake' },
      { from: 'reg',     to: 'perc' },
      { from: 'perc',    to: 'aff' },
      { from: 'aff',     to: 'mem' },
      { from: 'mem',     to: 'exec',  label: 'context', fromSide: 'b', toSide: 't', via: { x: 720, y: 712 } },
      { from: 'exec',    to: 'agen' },
      { from: 'agen',    to: 'metac' },
      { from: 'metac',   to: 'soc' },
      { from: 'agen',    to: 'stem2', dash: true, label: 'outbox', fromSide: 't', toSide: 'b', reach: 30, at: 0.75 },
      { from: 'metac',   to: 'exec',  dash: true, label: 'writes back into the apparatus', fromSide: 'b', toSide: 'b', reach: 60, at: 0.5 },
    ],
  },
]

for( const g of graphs ){
  const svg = render( g )
  writeFileSync( join( OUT, g.file ), svg )
  console.log( `✓ ${ g.file }  (${ ( svg.length / 1024 ).toFixed( 1 ) } KB)` )
}
console.log( `\n${ graphs.length } graphs → docs/graphs/` )
